import { test, expect } from '@playwright/test'

test('대시보드 필터와 팀·학생 상세 이동 및 승인 상태가 연결된다',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'수업 대시보드',exact:true}).click()
  await expect(page.getByRole('heading',{name:'수업 대시보드',exact:true})).toBeVisible()
  await page.getByLabel('프로젝트',{exact:true}).selectOption('vlan')
  await page.getByLabel('기간',{exact:true}).selectOption('recent')
  await expect(page.locator('.project-progress-list')).not.toContainText('네트워크 장애 진단')
  await page.locator('.project-progress-list button').click()
  await expect(page.getByLabel('진행 중인 과제')).toHaveValue('vlan')
  await page.getByRole('button',{name:'수업 대시보드',exact:true}).click()
  await page.getByRole('button',{name:'승인 검토 →',exact:true}).click()
  await expect(page.getByRole('region',{name:'선택 팀 상세'})).toContainText('3팀')
  await page.getByRole('button',{name:'승인',exact:true}).click()
  await page.getByRole('button',{name:'수업 대시보드',exact:true}).click()
  await expect(page.getByRole('button',{name:'승인 검토 →',exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:'학생 보기 →',exact:true}).click()
  await expect(page.getByLabel('학생 선택')).toHaveValue('이서연')
})

test('학교 기준은 선택·수정 후 적용하고 저장한 기준을 새 프로젝트에 재사용한다',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'과목 설정',exact:true}).click()
  await page.getByRole('button',{name:/학교 시스템에서 불러오기/}).click()
  await page.getByRole('button',{name:'NEIS에서 불러오기',exact:true}).click()
  const modal=page.getByRole('dialog')
  await modal.getByLabel('과목 기본 정보 추출 내용').fill('정보 네트워크 실습')
  await modal.getByLabel('학습 목표 추출 내용').fill('설정과 검증을 연결해 설명한다.')
  await modal.getByLabel('평가 요소 추출 내용').fill('문제 이해 | 40\n검증 | 40\n협업 | 20')
  await modal.getByRole('checkbox',{name:/NCS 능력단위/}).uncheck()
  await modal.getByRole('button',{name:'선택 항목 적용'}).click()
  await expect(page.getByLabel('과목명',{exact:true})).toHaveValue('정보 네트워크 실습')
  await expect(page.getByLabel('현재 수업')).toContainText('2학년 네트워크 실습')
  await page.getByRole('button',{name:'AI 운영 기본 정책',exact:true}).click()
  await page.getByRole('button',{name:'AI 자동',exact:true}).click()
  await page.getByRole('button',{name:'적극',exact:true}).click()
  await page.getByRole('button',{name:'과목 설정 저장',exact:true}).click()
  await expect(page.getByLabel('현재 수업')).toContainText('정보 네트워크 실습')
  await page.reload()
  await page.getByRole('button',{name:'과목 설정',exact:true}).click()
  await expect(page.getByLabel('과목명',{exact:true})).toHaveValue('정보 네트워크 실습')
  await page.getByRole('button',{name:'이 기준으로 새 프로젝트',exact:true}).click()
  await expect(page.getByLabel('반영 비율 1',{exact:true})).toHaveValue('40')
  await expect(page.getByRole('button',{name:'설정과 검증을 연결해 설명한다.',exact:true})).toBeVisible()
  await page.getByLabel('과제명').fill('새 실습')
  await page.getByRole('textbox',{name:'과제 설명',exact:true}).fill('과제의 수행과 결과를 비교합니다.')
  await page.getByRole('button',{name:'AI 운영 방식 설정',exact:true}).click()
  await expect(page.getByRole('tab',{name:'AI 자동',exact:true})).toHaveAttribute('aria-selected','true')
  await expect(page.getByRole('button',{name:/^적극 수행 단계마다/})).toHaveAttribute('aria-pressed','true')
})

test('문서 재업로드는 비교 후 적용하고 잘못된 파일과 평가 비율을 막는다',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'과목 설정',exact:true}).click()
  await page.getByRole('button',{name:'기준 문서 관리',exact:true}).click()
  await page.getByRole('button',{name:'다시 업로드',exact:true}).first().click()
  await page.locator('input[type=file]').setInputFiles({name:'수업계획서_개정.pdf',mimeType:'application/pdf',buffer:Buffer.from('demo only')})
  await page.getByRole('button',{name:'분석 결과 확인',exact:true}).click()
  await expect(page.getByRole('dialog')).toContainText('현재 설정')
  await page.getByLabel('평가 요소 추출 내용').fill('검증 | 20')
  await page.getByRole('button',{name:'선택 항목 적용',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('합계를 100')
  await page.getByLabel('평가 요소 추출 내용').fill('검증 | 100')
  await page.getByRole('button',{name:'선택 항목 적용',exact:true}).click()
  await expect(page.locator('.settings-form')).toContainText('수업계획서_개정.pdf')
  await expect(page.locator('.settings-form')).not.toContainText('네트워크실습 수업계획서.pdf')
  await page.locator('input[type=file]').setInputFiles({name:'bad.exe',mimeType:'application/octet-stream',buffer:Buffer.from('bad')})
  await expect(page.getByRole('alert')).toContainText('10MB 이하')
})

test('수업 대시보드와 과목 설정의 데스크톱·태블릿 화면',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'})
  for(const [width,height] of [[1440,1080],[1180,820],[820,1180],[390,844]]){
    await page.setViewportSize({width,height});await page.goto('/')
    if(width<=1050)await page.getByRole('button',{name:'수업 메뉴 열기'}).click()
    await page.getByRole('button',{name:'수업 대시보드',exact:true}).click()
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    await page.screenshot({path:`.impeccable/review/dashboard-${width}.png`,fullPage:true})
    if(width<=1050)await page.getByRole('button',{name:'수업 메뉴 열기'}).click()
    await page.getByRole('button',{name:'과목 설정',exact:true}).click()
    await page.getByRole('button',{name:/문서로 설정하기/}).click()
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    await page.screenshot({path:`.impeccable/review/course-settings-${width}.png`,fullPage:true})
    if(width===1440){await page.getByRole('button',{name:'예시 문서로 체험'}).click();await page.getByRole('button',{name:'분석 결과 확인'}).click();await page.screenshot({path:'.impeccable/review/course-import.png'})}
  }
})

test('설정 초안을 보존하고 새 프로젝트가 기존 수업 기록을 덮어쓰지 않는다',async({page})=>{
  await page.goto('/')
  const original=await page.getByLabel('과제명').inputValue()
  await page.getByRole('button',{name:'과목 설정',exact:true}).click()
  await page.getByLabel('과목명',{exact:true}).fill('보존할 설정 초안')
  await page.getByRole('button',{name:'수업 대시보드',exact:true}).click()
  await page.getByRole('button',{name:'과목 설정',exact:true}).click()
  await expect(page.getByLabel('과목명',{exact:true})).toHaveValue('보존할 설정 초안')
  await page.getByRole('button',{name:'교육과정 · 학습 목표',exact:true}).click()
  await page.getByLabel('핵심 역량 1',{exact:true}).fill('새로운 역량')
  await page.getByRole('button',{name:'과목 설정 저장',exact:true}).click()
  await page.getByRole('button',{name:'수업 대시보드',exact:true}).click()
  await expect(page.locator('.competence-bars')).toContainText('새로운 역량')
  await expect(page.locator('.competence-bars')).toContainText('미집계')
  await page.getByRole('button',{name:'과목 설정',exact:true}).click()
  await page.getByRole('button',{name:'이 기준으로 새 프로젝트',exact:true}).click()
  await page.getByLabel('과제명').fill('다른 새 프로젝트')
  await page.getByRole('button',{name:'팀별 모니터링',exact:true}).click()
  await expect(page.getByLabel('진행 중인 과제')).toContainText(original)
  await expect(page.getByLabel('진행 중인 과제')).not.toContainText('다른 새 프로젝트')
})
