import { test, expect } from '@playwright/test'

test('팀 승인과 학생 평가를 연결하고 학생별 평가를 저장한다', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '팀별 모니터링', exact: true }).click()
  await expect(page.getByRole('heading', { name: '팀별 모니터링', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^3팀 66%/ }).click()
  await page.getByRole('button', { name: '수정 후 승인', exact: true }).click()
  await page.getByLabel('학생에게 적용할 상황').fill('서로 다른 VLAN의 두 단말을 비교하고 결과를 설명해 보세요.')
  await page.getByRole('button', { name: '수정 내용 승인', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('수정 후 승인')
  await page.getByRole('button', { name: '박도윤', exact: true }).click()
  await expect(page.getByRole('heading', { name: '학생별 평가 지원', exact: true })).toBeVisible()
  await page.getByLabel('검증 교수자 판단').selectOption('충분')
  await page.getByLabel('교수자 피드백').fill('서로 다른 단말에서 검증한 근거를 잘 남겼습니다.')
  await page.getByRole('button', { name: '평가 저장', exact: true }).click()
  await page.getByLabel('학생 선택').selectOption('김민준')
  await expect(page.getByLabel('교수자 피드백')).toHaveValue('')
  await page.reload()
  await page.getByRole('button', { name: '학생별 평가 지원', exact: true }).click()
  await page.getByLabel('학생 검색').fill('박도윤')
  await page.getByLabel('학생 선택').selectOption('박도윤')
  await expect(page.getByLabel('교수자 피드백')).toHaveValue('서로 다른 단말에서 검증한 근거를 잘 남겼습니다.')
  await expect(page.getByLabel('검증 교수자 판단')).toHaveValue('충분')
  await page.getByRole('button', { name: '팀 보기', exact: true }).click()
  await expect(page.getByRole('region', { name: '선택 팀 상세' })).toContainText('3팀')
})

test('교수자 운영 화면의 데스크톱과 태블릿 레이아웃', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const [width,height] of [[1440,1080],[1180,820],[820,1180],[390,844]]) {
    await page.setViewportSize({width,height})
    await page.goto('/')
    if (width <= 1050) await page.getByRole('button', { name: '수업 메뉴 열기' }).click()
    await page.getByRole('button', { name: '팀별 모니터링', exact:true }).click()
    await expect(page.getByRole('heading', { name:'팀별 모니터링', exact:true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({path:`.impeccable/review/monitor-${width}.png`, fullPage:true})
    if (width <= 1050) await page.getByRole('button', { name: '수업 메뉴 열기' }).click()
    await page.getByRole('button', { name:'학생별 평가 지원', exact:true }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({path:`.impeccable/review/evaluation-${width}.png`, fullPage:true})
    await page.screenshot({path:`.impeccable/review/evaluation-first-${width}.png`})
    await page.evaluate(() => (document.activeElement as HTMLElement)?.blur())
    await page.locator('.competency-panel').screenshot({path:`.impeccable/review/competency-${width}.png`})
    await page.locator('#teacher-review').screenshot({path:`.impeccable/review/attainment-${width}.png`})
    await page.locator('#guidance-history').screenshot({path:`.impeccable/review/guidance-${width}.png`})
  }
})
