import { useRef, useState } from 'react'
import { guidanceOptions, modes } from './assignment'
import { defaultCourse, type Course } from './course'
type ImportRow = { key:'basic'|'goals'|'standards'|'ncs'|'criteria'|'curriculum'; label:string; value:string; original:string; selected:boolean }
const categories=['과목 기본 정보','교육과정 · 학습 목표','평가 운영 기준','AI 운영 기본 정책','수업 일정','기준 문서 관리']
const multiline=(s:string)=>s.split('\n').map(v=>v.trim()).filter(Boolean)
function importRows(c:Course):ImportRow[] {
  return [
    {key:'basic',label:'과목 기본 정보',value:c.name,original:`예시 수업계획서 1쪽 · 과목명: ${c.name}`},
    {key:'goals',label:'학습 목표',value:c.goals.join('\n'),original:'예시 2쪽 · 장애 원인을 설명하고, 진단 도구로 가설을 비교하며 수정 전후 결과를 검증한다. 팀의 역할을 수행하고 판단을 공유한다.'},
    {key:'standards',label:'성취기준',value:c.standards.join('\n'),original:'예시 3쪽 · 주소와 경로 해석 / 설정과 결과의 비교 / 검증 조건에 따른 해결 여부 설명'},
    {key:'ncs',label:'NCS 능력단위',value:c.ncs.join('\n'),original:'예시 3쪽 · 네트워크 구축 및 유지보수. 공식 능력단위 코드 검증은 연결 후 제공.'},
    {key:'criteria',label:'평가 요소',value:c.criteria.map(r=>`${r.name} | ${r.weight}`).join('\n'),original:'예시 4쪽 · 문제 이해 20, 해결 과정 30, 검증 20, 산출물 20, 협업 10. 총 100%.'},
    {key:'curriculum',label:'16주 수업 일정',value:c.curriculum.join('\n'),original:'예시 5쪽 · 기초 → 주소·서브넷 → VLAN·라우팅 → 진단·검증 → 통합 구축 → 발표·성찰'},
  ].map(r=>({...r,selected:true})) as ImportRow[]
}
export function CourseSettings({course,initialDraft,onDraftChange,onSave,onCreate}:{course:Course;initialDraft:Course;onDraftChange:(c:Course)=>void;onSave:(c:Course)=>void;onCreate:()=>void}) {
  const [draft,setDraft]=useState(()=>structuredClone(initialDraft)),[category,setCategory]=useState(0),[method,setMethod]=useState(''),[source,setSource]=useState(''),[rows,setRows]=useState<ImportRow[]>([]),[notice,setNotice]=useState(''),[error,setError]=useState(''),[dirty,setDirty]=useState(()=>JSON.stringify(initialDraft)!==JSON.stringify(course)),[files,setFiles]=useState<string[]>([]),[replacement,setReplacement]=useState('')
  const [reviewOpen,setReviewOpen]=useState(false)
  const dialog=useRef<HTMLDialogElement>(null),upload=useRef<HTMLInputElement>(null)
  function change<K extends keyof Course>(key:K,value:Course[K]) {const next={...draft,[key]:value};setDraft(next);onDraftChange(next);setDirty(true);setNotice('');setError('')}
  function reviewImport(label:string) {setSource(label);setRows(importRows(defaultCourse));setError('');setReviewOpen(true);dialog.current?.showModal()}
  function selectFiles(list:FileList|File[]|null) {
    if(!list?.length)return
    const items=Array.from(list)
    if(items.some(f=>! /\.(pdf|hwp|hwpx|docx|xlsx)$/i.test(f.name)||f.size>10*1024*1024)){setError('PDF, HWP, HWPX, DOCX, XLSX 파일을 10MB 이하로 선택해 주세요.');return}
    setFiles(items.map(f=>f.name));setMethod('document');setError('');setNotice('업로드 목록이 준비되었습니다. 데모 분석 예시를 확인해 주세요. 실제 파일 내용은 전송·분석하지 않습니다.')
  }
  function applyImport() {
    const next=structuredClone(draft)
    for(const row of rows.filter(r=>r.selected)) {
      if(!row.value.trim()){setError(`${row.label} 내용을 입력하거나 적용 대상에서 제외해 주세요.`);return}
      if(row.key==='basic')next.name=row.value.trim()
      else if(row.key==='criteria') {
        const criteria=multiline(row.value).map(line=>{const [name,value]=line.split('|');return {name:name.trim(),weight:Number(value)}})
        if(criteria.some(r=>!r.name||!Number.isFinite(r.weight)||r.weight<=0)||criteria.reduce((s,r)=>s+r.weight,0)!==100){setError('평가 요소는 요소명 | 비율 형식으로 입력하고 합계를 100으로 맞춰 주세요.');return}
        next.criteria=criteria
      } else next[row.key]=multiline(row.value)
    }
    const names=files.length?files:[source.includes('시스템')||source.includes('NEIS')?`${source} · 가져온 기준`:'공식 기준 예시']
    for(const name of names){const index=next.documents.findIndex(d=>d.name===(replacement||name));const doc={name,type:'가져온 기준',area:rows.filter(r=>r.selected).map(r=>r.label).join(' · '),updated:new Date().toISOString().slice(0,10)};if(index>=0)next.documents[index]=doc;else next.documents.push(doc)}
    setDraft(next);onDraftChange(next);setDirty(true);setNotice('선택한 항목을 설정 초안에 적용했습니다. 검토 후 과목 설정을 저장하세요.');setError('');setReplacement('');setFiles([]);dialog.current?.close()
  }
  function save() {
    if(!draft.name.trim()||!draft.start||!draft.end||draft.start>draft.end){setError('과목명과 수업 기간을 확인해 주세요.');return}
    if(!draft.goals.length||draft.goals.some(x=>!x.trim())||draft.curriculum.some(x=>!x.trim())){setError('학습 목표와 수업 일정의 빈 내용을 입력하거나 삭제해 주세요.');return}
    if(!draft.criteria.length||draft.criteria.some(c=>!c.name.trim()||!Number.isFinite(c.weight)||c.weight<=0)||draft.criteria.reduce((n,c)=>n+c.weight,0)!==100){setError('평가 요소를 입력하고 비율 합계를 100%로 맞춰 주세요.');return}
    if(!draft.guidance.length){setError('허용할 가이던스를 하나 이상 선택해 주세요.');return}
    try {localStorage.setItem('trace-course-v1',JSON.stringify(draft));onSave(structuredClone(draft));setDirty(false);setError('');setNotice('과목 설정을 저장했습니다. 새 프로젝트의 기본값으로 사용할 수 있습니다.')}catch{setError('저장 공간을 사용할 수 없습니다. 다시 시도해 주세요.')}
  }
  function stringList(key:'goals'|'standards'|'ncs'|'competencies') {return <div className="course-edit-list">{draft[key].map((value,i)=><div key={i}><input aria-label={`${key==='goals'?'학습 목표':key==='standards'?'성취기준':key==='competencies'?'핵심 역량':'NCS 능력단위'} ${i+1}`} value={value} onChange={e=>change(key,draft[key].map((s,j)=>j===i?e.target.value:s))}/><button className="icon-button remove" aria-label={`${key} ${i+1} 삭제`} onClick={()=>change(key,draft[key].filter((_,j)=>i!==j))}><span className="icon icon-close"/></button></div>)}<button className="text-button" onClick={()=>change(key,[...draft[key],''])}>+ 직접 추가</button></div>}
  return <div className="course-settings">
    <div className="settings-intro"><div><h2>한 학기의 기준을 한 곳에서</h2><p>기존 자료를 불러오고 확인하면, 다음 과제에서 다시 사용할 수 있습니다.</p></div><span className="teach-badge mint">{course.semester}</span></div>
    <div className="settings-start">{[['system','학교 시스템에서 불러오기','학사 · LMS · NEIS','grid'],['document','문서로 설정하기','수업계획서 · 평가계획 · NCS','download'],['manual','직접 설정하기','기본 정보부터 차근차근','edit']].map(([id,title,desc,icon],i)=><button key={id} className={`settings-start-card start-${i}`} aria-pressed={method===id} onClick={()=>{setMethod(id);setError('');if(id==='manual'){setCategory(0);document.getElementById('course-editor')?.scrollIntoView({behavior:'instant'})}}}><span className="coverage-orb"><span className={`icon icon-${icon}`}/></span><span><strong>{title}</strong><small>{desc}</small></span><span className="icon icon-right"/></button>)}</div>
    <div className="import-flow" aria-label="설정 적용 흐름"><span>자료 불러오기</span><span>AI 분석 · 분류</span><strong>교수자 확인 · 수정</strong><span>과목 기준으로 저장</span></div>
    {method==='system'&&<section className="panel source-panel"><div className="section-heading"><h2>학교 시스템 연결</h2><span className="count-label">시연 연결</span></div><p>연결된 과목의 기준을 선택해 가져오는 흐름입니다. 실제 기관 계정에는 접속하지 않습니다.</p><div className="system-choices">{['대학 정보시스템','LMS','학사 시스템','NEIS'].map(label=><button className="button secondary" key={label} onClick={()=>{setFiles([]);setReplacement('');reviewImport(`${label} 예시`)}}>{label}에서 불러오기</button>)}</div></section>}
    {method==='document'&&<section className="panel source-panel"><div className="section-heading"><h2>{replacement?'기준 문서 다시 업로드':'문서로 과목 설정'}</h2><span className="count-label">{replacement||'예시 분석'}</span></div><div className="course-dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();selectFiles(e.dataTransfer.files)}}><span className="icon icon-download"/><strong>수업에 쓰던 문서를 여기에 놓아주세요</strong><span>교육과정 · 강의계획서 · 평가 규정 · 자체 루브릭</span><small>HWP · HWPX · PDF · DOCX · XLSX / 파일당 10MB</small><button className="button secondary" onClick={()=>upload.current?.click()}>문서 선택</button><button className="text-button" onClick={()=>{setFiles(['2026_네트워크실습_수업계획서.pdf']);setNotice('예시 문서가 선택되었습니다.')}}>예시 문서로 체험</button></div>{files.length>0&&<div className="analysis-result"><div><strong>분석 예시 준비</strong><p>{files.join(' · ')}</p><small>과목 정보 · 목표 5개 · 성취기준 3개 · 평가 요소 5개 · 수업 일정 16주</small><p className="course-demo-note">파일 형식과 이름만 확인하며, 내용 분석은 준비된 예시로 보여 줍니다.</p></div><button className="button primary" onClick={()=>reviewImport(files.join(', '))}>분석 결과 확인</button></div>}</section>}
    <input ref={upload} type="file" hidden accept=".pdf,.hwp,.hwpx,.docx,.xlsx" multiple={!replacement} onChange={e=>{selectFiles(e.target.files);e.target.value=''}}/>
    {notice&&<p role="status" className="settings-notice">{notice}</p>}{error&&!reviewOpen&&<p role="alert" className="error-message">{error}</p>}
    <div id="course-editor" className="course-editor"><nav className="settings-tabs" aria-label="과목 설정 카테고리">{categories.map((c,i)=><button key={c} aria-pressed={category===i} onClick={()=>setCategory(i)}>{c}</button>)}</nav><section className="panel settings-form"><div className="section-heading"><h2>{categories[category]}</h2><span className="count-label">과목 기본값</span></div>
    {category===0&&<div className="settings-form-grid">{([['name','과목명'],['grade','학년'],['semester','학기'],['students','대상 학생 / 학급'],['start','수업 시작일'],['end','수업 종료일']] as const).map(([key,label])=><label className="field" key={key}>{label}<input type={key==='start'||key==='end'?'date':'text'} value={draft[key]} onChange={e=>change(key,e.target.value)}/></label>)}<label className="field full">과목 설명<textarea rows={3} value={draft.description} onChange={e=>change('description',e.target.value)}/></label><p className="course-demo-note full">학생 명부 연동은 예시이며, 운영 화면은 기존 24명·6팀의 가상 수업을 사용합니다.</p></div>}
    {category===1&&<><div className="settings-tools"><button className="button secondary" onClick={()=>{setFiles([]);setReplacement('');reviewImport('공식 교육과정 · NCS 예시')}}>공식 기준 불러오기</button><button className="text-button" onClick={()=>{setMethod('document');setReplacement('');upload.current?.click()}}>문서에서 가져오기</button></div><h3>교육과정 · 성취기준</h3>{stringList('standards')}<h3>NCS 능력단위</h3>{stringList('ncs')}<h3>교수자 학습 목표</h3>{stringList('goals')}<h3>대시보드 핵심 역량</h3><p className="section-note">관찰할 역량을 설정합니다. 새 역량은 연결된 증거가 수집되기 전까지 미집계로 표시됩니다.</p>{stringList('competencies')}</>}
    {category===2&&<><p className="section-note">과제 생성 시 불러온 뒤 과제별로 조정할 수 있습니다.</p><div className="course-criteria">{draft.criteria.map((c,i)=><div key={i}><input aria-label={`과목 평가 요소 ${i+1}`} value={c.name} onChange={e=>change('criteria',draft.criteria.map((x,j)=>i===j?{...x,name:e.target.value}:x))}/><input type="number" min="1" max="100" aria-label={`과목 반영 비율 ${i+1}`} value={c.weight||''} onChange={e=>change('criteria',draft.criteria.map((x,j)=>i===j?{...x,weight:Number(e.target.value)}:x))}/><span>%</span><button className="icon-button remove" aria-label={`과목 평가 요소 ${i+1} 삭제`} onClick={()=>change('criteria',draft.criteria.filter((_,j)=>j!==i))}><span className="icon icon-close"/></button></div>)}</div><div className="settings-tools"><button className="text-button" onClick={()=>change('criteria',[...draft.criteria,{name:'',weight:0}])}>+ 평가 요소 추가</button><strong>합계 {draft.criteria.reduce((n,c)=>n+c.weight,0)}%</strong></div><div className="settings-checks"><label><input type="checkbox" checked={draft.selfReview} onChange={e=>change('selfReview',e.target.checked)}/>자기평가 사용</label><label><input type="checkbox" checked={draft.peerReview} onChange={e=>change('peerReview',e.target.checked)}/>동료평가 사용</label></div></>}
    {category===3&&<><p className="section-note">새 프로젝트 생성 시 기본값으로 적용되며 과제별로 변경할 수 있습니다.</p><fieldset><legend>운영 방식</legend><div className="compact-tabs settings-segment">{modes.map(m=><button aria-pressed={draft.mode===m} key={m} onClick={()=>change('mode',m)}>{m}</button>)}</div></fieldset><fieldset><legend>가이던스 기본 수준</legend><div className="compact-tabs settings-segment">{['최소','보통','적극'].map(m=><button aria-pressed={draft.intervention===m} key={m} onClick={()=>change('intervention',m)}>{m}</button>)}</div></fieldset><h3>허용할 지원 유형</h3><div className="settings-checks">{guidanceOptions.map(g=><label key={g}><input type="checkbox" checked={draft.guidance.includes(g)} onChange={()=>change('guidance',draft.guidance.includes(g)?draft.guidance.filter(x=>x!==g):[...draft.guidance,g])}/>{g}</label>)}</div><label className="direct-answer-policy"><input type="checkbox" checked={draft.directAnswers} onChange={e=>change('directAnswers',e.target.checked)}/><span>직접 답안 제공 허용<small>기본값은 허용 안 함 · 데모에서는 정책 설정만 저장합니다.</small></span></label></>}
    {category===4&&<><p className="section-note">주차 내용을 직접 편집하거나 위·아래 버튼으로 순서를 변경하세요.</p><div className="curriculum-rows">{draft.curriculum.map((text,i)=><div key={i}><span>{i+1}주차</span><input aria-label={`${i+1}주차 수업 내용`} value={text} onChange={e=>change('curriculum',draft.curriculum.map((v,j)=>j===i?e.target.value:v))}/><button className="icon-button" disabled={i===0} aria-label={`${i+1}주차 위로`} onClick={()=>{const a=[...draft.curriculum];[a[i-1],a[i]]=[a[i],a[i-1]];change('curriculum',a)}}>↑</button><button className="icon-button" disabled={i===draft.curriculum.length-1} aria-label={`${i+1}주차 아래로`} onClick={()=>{const a=[...draft.curriculum];[a[i+1],a[i]]=[a[i],a[i+1]];change('curriculum',a)}}>↓</button><button className="icon-button remove" aria-label={`${i+1}주차 삭제`} onClick={()=>change('curriculum',draft.curriculum.filter((_,j)=>i!==j))}><span className="icon icon-close"/></button></div>)}</div><button className="text-button" onClick={()=>change('curriculum',[...draft.curriculum,''])}>+ 주차 추가</button></>}
    {category===5&&<><div className="table-scroll"><table className="reference-table"><thead><tr><th>문서명</th><th>유형 / 적용 영역</th><th>업데이트</th><th>관리</th></tr></thead><tbody>{draft.documents.map((d,i)=><tr key={`${d.name}-${i}`}><th>{d.name}</th><td>{d.type}<small className="doc-area">{d.area}</small></td><td>{d.updated}</td><td><button className="text-button" onClick={()=>{setReplacement(d.name);setFiles([]);setMethod('document');upload.current?.click()}}>다시 업로드</button></td></tr>)}</tbody></table></div><button className="text-button" onClick={()=>{setReplacement('');setMethod('document');upload.current?.click()}}>+ 문서 추가</button><p className="course-demo-note">문서 원본은 서버에 업로드하지 않습니다. 연결 문서의 이름과 적용 내역만 이 브라우저에 저장됩니다.</p></>}
    </section></div><div className="settings-footer"><span>{dirty?'저장하지 않은 변경사항':'이 브라우저에 저장된 과목 기준'}</span><div><button className="button secondary" disabled={dirty} onClick={onCreate}>이 기준으로 새 프로젝트</button><button className="button primary" onClick={save}>과목 설정 저장</button></div></div>
    <dialog ref={dialog} onClose={()=>setReviewOpen(false)} className="course-import-dialog"><div className="section-heading"><h2>{replacement?'기존 설정과 변경사항 비교':'불러온 항목 확인'}</h2><button className="text-button" onClick={()=>{dialog.current?.close();setError('')}}>닫기</button></div><p>{source}</p><p className="course-demo-note">시연용 추출 예시 · 실제 기관 데이터나 업로드 파일의 원문이 아닙니다. 적용할 항목만 선택하고 내용을 수정하세요.</p><div className="import-review-head"><span>AI 추출 내용 · 수정 가능</span><span>{replacement?'현재 설정 / 예시 원문 근거':'예시 원문 근거'}</span></div>{rows.map((r,i)=><div className="import-review-row" key={r.key}><div><label className="import-toggle"><input type="checkbox" checked={r.selected} onChange={e=>setRows(rows.map((x,j)=>i===j?{...x,selected:e.target.checked}:x))}/>{r.label}<small>{r.selected?'적용':'제외'}</small></label><textarea aria-label={`${r.label} 추출 내용`} rows={r.key==='curriculum'?5:3} value={r.value} onChange={e=>setRows(rows.map((x,j)=>i===j?{...x,value:e.target.value}:x))}/>{r.key==='criteria'&&<small>요소명 | 비율 · 한 줄에 한 요소</small>}</div><div className="original-evidence">{replacement&&<><strong>현재 설정</strong><p>{r.key==='basic'?draft.name:r.key==='criteria'?draft.criteria.map(c=>`${c.name} ${c.weight}%`).join(' · '):draft[r.key].join(' · ')}</p><strong>새 문서의 예시 근거</strong></>}<p>{r.original}</p></div></div>)}{error&&<p role="alert" className="error-message">{error}</p>}<div className="import-review-footer"><span>{rows.filter(r=>r.selected).length}개 영역 선택</span><button className="button primary" disabled={!rows.some(r=>r.selected)} onClick={applyImport}>선택 항목 적용</button></div></dialog>
  </div>
}
