import { useWorkspace } from './WorkspaceContext'
import { useState } from 'react'
import type { Assignment } from './assignment'
import { demoStudents, guidanceOptions } from './assignment'
import { ProgressRing } from './TeachingCharts'
import { dashboardProjects, type Course, type TeachingTarget } from './course'
import type { TeachingView } from './TeachingWorkspace'
export function CourseDashboard({course,assignment,decisions,onOpen}:{course:Course;assignment:Assignment;decisions:Record<string,string>;onOpen:(view:TeachingView,target:TeachingTarget)=>void}) {
  const {scenario:s}=useWorkspace()
  const teachingTeams=s.teams
  const [project,setProject]=useState('all'),[period,setPeriod]=useState('semester'),[scope,setScope]=useState('전체'),[subject,setSubject]=useState('1')
  const projects=dashboardProjects(assignment.title).map((p,i)=>({...p,short:i===0?assignment.title:s.projectNames[i]})), selected=projects.filter(p=>project==='all'||p.id===project)
  const weekly=Array.from({length:7},(_,i)=>Math.round(selected.reduce((n,p)=>n+p.weekly[i],0)/selected.length))
  const support=guidanceOptions.map((_,i)=>selected.reduce((n,p)=>n+p.support[i],0))
  const shownSupport=support.map((n,i)=>period==='recent'?selected.reduce((sum,p)=>sum+Math.round(p.support[i]*.6),0):n), totalSupport=shownSupport.reduce((a,b)=>a+b,0)
  const average=weekly[6],pending=project!=='vlan'&&assignment.mode==='교수자 승인형'&&!decisions['current-3']?1:0
  const weeks=period==='recent'?[3,4,5,6]:[0,1,2,3,4,5,6]
  const targetTask=project==='all'?'current':project
  const competenceNames=course.competencies
  const demoCompetencies=['문제 이해','원인 분석','해결 전략 수립','검증','협업']
  const base=[82,74,69,58,77], subjectIndex=scope==='팀별'?Number(subject)-1:scope==='학생별'?demoStudents.indexOf(subject)%6:0
  const rates=competenceNames.map(label=>{const n=base[demoCompetencies.indexOf(label)];return n===undefined?null:Math.max(25,Math.min(98,n+(scope==='전체'?0:[7,-9,3,-18,10,-3][Math.max(0,subjectIndex)])+(project==='vlan'?-5:0)))})
  const points=(values:number[])=>weeks.map((w,i)=>`${45+i*495/(weeks.length-1)},${190-values[w]*1.6}`).join(' ')
  return <div className="course-dashboard">
    <div className="dashboard-top"><div><h2>{course.name}</h2><p>{course.semester} · 학생 24명 · 6팀</p></div><div className="dashboard-filters"><label>프로젝트<select aria-label="프로젝트" value={project} onChange={e=>setProject(e.target.value)}><option value="all">전체 프로젝트</option>{projects.map(p=><option key={p.id} value={p.id}>{p.short}</option>)}</select></label><label>기간<select aria-label="기간" value={period} onChange={e=>setPeriod(e.target.value)}><option value="semester">학기 전체</option><option value="recent">최근 4주</option></select></label></div></div>
    <p className="course-demo-note">가상 수업 데이터 · 현재 7주차 · 기간 필터는 추이와 AI 지원 통계에 적용됩니다.</p>
    <div className="dashboard-stats">{[['진행 중 과제',selected.length,'개','mint'],['전체 학생',24,'명','lavender'],['확인 필요',2,'팀','yellow'],['AI 승인 대기',pending,'건','rose']].map(([label,value,unit,color])=><div className="panel dashboard-stat" key={label}><span>{label}</span><div><strong>{value}<small>{unit}</small></strong><span className={`stat-square ${color}`}><span className={`icon icon-${label==='전체 학생'?'users':label==='진행 중 과제'?'edit':'list'}`} /></span></div></div>)}<div className="panel dashboard-stat average-stat"><span>평균 과제 진행률</span><ProgressRing value={average} label="전체 과제 평균 진행률" /></div></div>
    <div className="dashboard-grid">
      <section className="panel"><div className="section-heading"><h2>과제별 진행 현황</h2><span className="count-label">현재 누적</span></div><div className="project-progress-list">{selected.map((p,i)=><button key={p.id} onClick={()=>onOpen('monitoring',{task:p.id,team:2})}><span><strong>{p.short}</strong><b>{p.weekly[6]}%</b></span><span className="dashboard-bar"><i className={`chart-fill-${i}`} style={{width:`${p.weekly[6]}%`}} /></span><small>6팀 · 팀 진행 현황 보기 <span className="icon icon-right" /></small></button>)}</div><div className="chart-footnote">진행률은 현재 수행 단계의 요약입니다.</div></section>
      <section className="panel"><div className="section-heading"><h2>주차별 학습 진행률</h2><span className="count-label">7주차</span></div><div className="chart-key"><span><i className="chart-fill-0" />실제 진행</span><span><i className="chart-neutral" />계획 진행</span></div><svg className="semester-chart" viewBox="0 0 565 225" role="img" aria-label={`주차별 실제 진행률 ${weeks.map(w=>`${w+1}주차 ${weekly[w]}%`).join(', ')}, 계획 ${weeks.map(w=>`${(w+1)*10}%`).join(', ')}`}>
      {[0,25,50,75,100].map(n=><g key={n}><line x1="45" x2="540" y1={190-n*1.6} y2={190-n*1.6}/><text x="32" y={194-n*1.6} textAnchor="end">{n}</text></g>)}<polyline className="planned" points={points([10,20,30,40,50,60,70])}/><polyline className="actual" points={points(weekly)}/>{weeks.map((w,i)=><g key={w}><circle cx={45+i*495/(weeks.length-1)} cy={190-weekly[w]*1.6} r="4"/><text x={45+i*495/(weeks.length-1)} y="215" textAnchor="middle">{w+1}주</text></g>)}</svg></section>
      <section className="panel dashboard-ai"><div className="section-heading"><h2>과제별 AI 지원</h2><span className="count-label">{period==='recent'?'최근 4주':'학기 누적'} · {totalSupport}회</span></div><div className="ai-analysis"><div>{selected.map(p=>{const counts=p.support.map(n=>period==='recent'?Math.round(n*.6):n);return <div className="project-support" key={p.id}><h3>{p.short}</h3><div className="support-stacked-bar" role="img" aria-label={counts.map((n,i)=>`${guidanceOptions[i]} ${n}회`).join(', ')}>{counts.map((n,i)=><span key={i} className={`chart-fill-${i}`} style={{flex:n}} title={`${guidanceOptions[i]} ${n}회`}>{n}</span>)}</div></div>})}<p className="chart-footnote">지원 형태를 비교합니다. 사용량이 성과를 뜻하지는 않습니다.</p></div><div className="support-donut-wrap"><svg className="support-donut" viewBox="0 0 120 120" role="img" aria-label={`AI 지원 분포 ${shownSupport.map((n,i)=>`${guidanceOptions[i]} ${Math.round(n/totalSupport*100)}%`).join(', ')}`}>{shownSupport.map((n,i)=>{const start=shownSupport.slice(0,i).reduce((a,b)=>a+b,0)/totalSupport*100;return <circle key={i} className={`donut-segment donut-${i}`} cx="60" cy="60" r="46" pathLength="100" strokeDasharray={`${n/totalSupport*100} ${100-n/totalSupport*100}`} strokeDashoffset={-start} transform="rotate(-90 60 60)"/>})}<text x="60" y="58" textAnchor="middle">{totalSupport}</text><text className="donut-sub" x="60" y="76" textAnchor="middle">지원 기록</text></svg></div></div><div className="support-legend">{guidanceOptions.map((g,i)=><span key={g}><i className={`chart-fill-${i}`}/>{g}<b>{Math.round(shownSupport[i]/totalSupport*100)}%</b></span>)}</div></section>
      <section className="panel"><div className="section-heading"><h2>핵심 역량 관찰 현황</h2><div className="compact-tabs">{['전체','팀별','학생별'].map(s=><button aria-pressed={scope===s} key={s} onClick={()=>{setScope(s);setSubject(s==='학생별'?demoStudents[0]:'1')}}>{s}</button>)}</div></div>{scope!=='전체'&&<select className="competency-subject" aria-label="역량 조회 대상" value={subject} onChange={e=>setSubject(e.target.value)}>{(scope==='팀별'?teachingTeams.map(t=>String(t.id)):demoStudents).map(v=><option key={v} value={v}>{scope==='팀별'?`${v}팀`:v}</option>)}</select>}<div className="competence-bars">{competenceNames.map((label,i)=><div key={label}><span>{label}</span><span className="dashboard-bar"><i className={`chart-fill-${i%5}`} style={{width:`${rates[i]??0}%`}} /></span><strong>{rates[i]===null?'미집계':`${rates[i]}%`}</strong></div>)}</div><p className="chart-footnote">과정증거에서 기준에 부합하는 수행이 관찰된 비율의 시연 예시입니다. 확정 성적이 아닙니다.</p></section>
    </div>
    <div className="dashboard-bottom"><section className="panel"><div className="section-heading"><h2>지금 확인할 항목</h2><span className="count-label">{pending+2}건</span></div><table className="reference-table intervention-table"><thead><tr><th>대상</th><th>확인 이유</th><th>이동</th></tr></thead><tbody><tr><th>2팀</th><td>18분간 후속 수행 없음 · 검증 결과 미수집</td><td><button className="text-button" onClick={()=>onOpen('monitoring',{task:targetTask,team:2})}>팀 보기 →</button></td></tr><tr><th>이서연</th><td>수정 이후 검증 근거 확인 필요</td><td><button className="text-button" onClick={()=>onOpen('evaluation',{task:targetTask,student:'이서연'})}>학생 보기 →</button></td></tr>{pending>0&&<tr><th>3팀</th><td>검증 범위를 넓히는 AI 상황 제안</td><td><button className="text-button" onClick={()=>onOpen('monitoring',{task:'current',team:3})}>승인 검토 →</button></td></tr>}</tbody></table></section><section className="panel"><div className="section-heading"><h2>최근 주요 활동</h2><span className="count-label">현재 수업</span></div><ol className="event-timeline dashboard-timeline"><li><time>14:29</time><span>5팀 · 수정 전후 검증 결과 정리</span></li>{project!=='vlan'&&<li><time>14:28</time><span>3팀 · {pending?'AI 상황 제안 승인 요청':'검증 범위 확장 검토'}</span></li>}<li><time>14:26</time><span>1팀 · 실행·검증 결과 공유</span></li><li><time>14:13</time><span>이서연 · 다음 검증 계획 기록</span></li></ol></section></div>
  </div>
}
