import { useRef } from 'react'
import type { Assignment } from './assignment'
type Environment = Assignment['environment']
const environmentNames = { workspace:'프로젝트 작업공간', network:'연결된 실습 모듈', external:'외부 도구 · 현장 실습' }
export function ExecutionEnvironment({ value, onChange }: { value:Environment; onChange:(value:Environment)=>void }) {
  return <div className="execution-environment"><div className="environment-options">{(Object.keys(environmentNames) as Environment['kind'][]).map(kind=><button type="button" key={kind} aria-pressed={value.kind===kind} onClick={()=>onChange({...value,kind})}><strong>{environmentNames[kind]}</strong><small>{kind==='workspace'?'토론 · 문서 · 산출물 중심':kind==='network'?'네트워크 등 과목별 실습 환경':'외부 프로그램 또는 실제 장비'}</small></button>)}</div>
    {value.kind==='network' && <div className="environment-settings"><div className="field"><label htmlFor="lab-template">실습 템플릿</label><select id="lab-template" value={value.template} onChange={e=>onChange({...value,template:e.target.value})}><option>정적 라우팅 장애 진단</option><option>VLAN 소속 오류 진단</option></select></div><div className="environment-capabilities"><strong>이 모듈에서 확인할 수 있는 증거</strong><p>명령 실행 · 설정 변경 · 통신 검증 결과</p><small>학생의 판단·설명과 연결해 공통 평가 지원 화면에 표시합니다.</small></div></div>}
    {value.kind==='external' && <div className="environment-settings"><div className="field"><label htmlFor="lab-url">실습 도구 주소 <span className="count-label">선택</span></label><input id="lab-url" type="url" placeholder="https://" value={value.url} onChange={e=>onChange({...value,url:e.target.value})} /></div><div className="field"><label htmlFor="lab-instructions">실습 안내</label><textarea id="lab-instructions" rows={2} placeholder="실행할 도구와 결과를 남기는 방법을 안내하세요." value={value.instructions} onChange={e=>onChange({...value,instructions:e.target.value})} /></div></div>}
    <div className="environment-footnote"><span className="teach-badge mint">공통 학습 과정</span><span>판단 → 실행·수정 → 검증 → Learning Evidence</span></div><p className="micro-note">{value.kind==='network'?'현재는 모듈 연결을 보여주는 UI 데모입니다. 실제 장비 제어·명령 실행은 연결 모듈이 담당합니다.':value.kind==='external'?'연동되지 않은 외부 활동은 자동 수집되지 않습니다. 학생이 결과 파일과 설명을 제출합니다.':'작업공간의 문서 변경·팀 공유·산출물을 학생 설명과 함께 모읍니다.'}</p>
  </div>
}
export function EnvironmentPreview({ value }: { value:Environment }) {
  const dialog=useRef<HTMLDialogElement>(null)
  const vlan = value.template.includes('VLAN')
  const devices = vlan ? [['PC-A','192.168.10.10'],['SW1','VLAN 10 / 20'],['PC-B','192.168.10.20']] : [['PC-A','192.168.10.10'],['R1','10.0.0.1'],['R2','10.0.0.2'],['PC-B','192.168.20.10']]
  const safeUrl = /^https?:\/\//i.test(value.url) ? value.url : ''
  return <section className="environment-preview"><h3>과제 수행 환경</h3><div className="environment-preview-row"><div><strong>{value.kind==='network'?value.template:environmentNames[value.kind]}</strong><p>{value.kind==='network'?'실습 명령과 검증 결과가 나의 과정증거로 연결됩니다.':value.kind==='external'?value.instructions||'외부 도구에서 실습한 결과와 설명을 제출합니다.':'팀 문서와 산출물을 작성하고 판단 근거를 남깁니다.'}</p></div>{value.kind==='network'?<button type="button" className="button secondary" onClick={()=>dialog.current?.showModal()}>실습 환경 미리보기</button>:value.kind==='external'&&safeUrl?<a className="button secondary" href={safeUrl} target="_blank" rel="noreferrer">실습 도구 열기</a>:null}</div>
    {value.kind==='network' && <dialog ref={dialog} aria-label="실습 환경 미리보기" className="teaching-dialog lab-preview-dialog"><div className="section-heading"><h2>{value.template}</h2><button className="text-button" onClick={()=>dialog.current?.close()}>닫기</button></div><p className="micro-note">시연용 실습 환경 · 실제 명령은 실행되지 않습니다.</p><div className="network-topology" aria-label={vlan ? "PC-A와 PC-B가 SW1에 연결된 네트워크" : "PC-A에서 R1, R2를 거쳐 PC-B까지의 네트워크 경로"}>{devices.map(([name,address])=><div key={name}><span>{name}</span><small>{address}</small></div>)}</div><div className="lab-demo-content"><strong>문제 상황</strong><p>{value.template.includes('VLAN')?'같은 부서의 두 단말이 서로 통신하지 못합니다. VLAN 소속을 실제 구성과 비교하세요.':'본사와 지사 간 통신이 실패합니다. 양방향 경로를 진단하고 수정 결과를 검증하세요.'}</p><pre>{vlan ? 'SW1# show vlan brief\n10 STAFF active Fa0/1\n20 GUEST active Fa0/2\nPC-A> ping 192.168.10.20\nRequest timed out.' : 'PC-A> ping 192.168.20.10\nRequest timed out.\nPackets: Sent = 4, Received = 0'}</pre><strong>다음 판단</strong><p>어느 구간까지 정상인지 먼저 확인하고, 원인 후보와 검증 방법을 기록합니다.</p><span className="teach-badge mint">학생 판단 + 모듈 수행 기록 → Learning Evidence</span></div></dialog>}
  </section>
}
