import { studentInitial, type StudentState } from './student'
export const fusionStorage='trace-fusion-workspace-v1'
export const fusionRubric=[{name:'문제 정의',weight:20},{name:'지식 연결·전이',weight:25},{name:'설계·구현 과정',weight:25},{name:'검증·성찰',weight:20},{name:'협업',weight:10}]
export const fusionConnections=[
 {name:'데이터베이스',source:'이전 학기',known:'테이블과 기본 SQL',need:'문서·출처·수정일을 연결하는 데이터 구조',action:'안내문 5개의 출처를 작은 테이블로 모델링',status:'적용 중'},
 {name:'웹 프로그래밍',source:'이번 학기',known:'폼 입력과 화면 구성',need:'요청·응답과 오류 상태 처리',action:'API 없이 고정 JSON으로 답변·빈 결과 화면 만들기',status:'작은 실험'},
 {name:'UX · 의사소통',source:'다른 교과',known:'사용자 인터뷰와 질문 구체화',need:'학생의 실제 질문과 성공 기준 정의',action:'재학생 3명의 질문을 분류하고 평가 문항으로 전환',status:'근거 확보'},
 {name:'AI · 정보 탐색',source:'새로 탐색',known:'프롬프트로 질문하기',need:'검색 근거와 생성 답변을 구분하는 방법',action:'자료에 없는 질문에서 답변을 보류하는 실험',status:'지도 필요'},
 {name:'정보 윤리',source:'다른 교과',known:'개인정보 최소 수집',need:'질문 로그에 식별 정보가 남지 않는 설계',action:'학번이 포함된 입력의 마스킹 기준 작성',status:'확인 필요'},
]
export const fusionTeams=[
 {id:1,name:'캠퍼스 길잡이',problem:'흩어진 학교 안내를 찾기 어려운 학생',result:'출처를 확인할 수 있는 학교 안내 도우미',progress:58,stage:'프로토타입 검증',state:'확인 필요',tech:'TypeScript · React · Python · FastAPI',gap:'자료에 없는 질문에 대한 응답 정책',connections:['데이터베이스','웹 프로그래밍','UX','정보 윤리'],reason:'답변 생성보다 자료 검색과 출처 검증을 먼저 분리할 필요가 있습니다.'},
 {id:2,name:'공유물품 연결소',problem:'팀별로 남는 실습 재료와 부족한 재료의 불균형',result:'조건을 설명하는 재료 매칭 서비스',progress:42,stage:'기술 선택·범위 조정',state:'승인 대기',tech:'Python · Streamlit · SQLite',gap:'거리·수량·우선순위 조건의 비교 방법',connections:['수학','데이터베이스','사용자 조사'],reason:'모든 조건을 최적화하기 전에 가장 중요한 조건 하나로 기준 모델을 만들도록 제안했습니다.'},
 {id:3,name:'학습 회고 노트',problem:'활동 기록은 있지만 다음 계획으로 연결하지 못하는 학습자',result:'자기 설명을 돕는 회고 질문 도구',progress:74,stage:'사용자 검증',state:'정상',tech:'TypeScript · React · Node.js',gap:'사용자가 스스로 작성한 성찰과 AI 문장의 구분',connections:['교육학','통계','웹 프로그래밍'],reason:'회고 질문 전후의 학생 설명을 비교하고 있습니다. AI 표현의 양을 성과로 계산하지 않습니다.'},
]
export const fusionStudents=[{name:'유송민',role:'API·데이터 연결',strength:'이전 학기의 테이블 설계를 안내문 출처 구조에 적용',gap:'비동기 요청과 근거 없는 질문 처리',evidence:['자료 구조 설계','고정 응답 API 계약'],points:[17,18,17,null,8]},{name:'김민수',role:'사용자 조사·문제 정의',strength:'인터뷰 질문을 사용자 요구와 연결',gap:'인터뷰 표본 범위 설명',evidence:['인터뷰 요약','사용자 요구 비교표'],points:[18,19,16,12,8]},{name:'이서연',role:'UX·프런트엔드',strength:'답변과 출처를 함께 확인하는 화면 구현',gap:'빈 결과와 오류 상태 구분',evidence:['와이어프레임','오류 상태 화면'],points:[16,20,21,13,9]},{name:'박지훈',role:'검증·통합',strength:'정상·미등록 질문을 구분한 검증 계획',gap:'실제 사용자 검증 결과 수집',evidence:['검증 문항 목록','사용자 테스트 계획'],points:[16,18,19,null,8]}]
export type FusionEvidence={title:string;detail:string;owner:string;source:string;criterion:string;time:string}
export type FusionData={
 brief:string;rubric:typeof fusionRubric;plan:{name:string;problem:string;audience:string;scope:string;language:string;frontend:string;backend:string;tools:string;reason:string};connections:typeof fusionConnections;completed:string[];experiment:boolean;experimentNote:string;evidence:FusionEvidence[];student:StudentState;guidance:{level:number;topic:string;time:string}[];request:string;teacherFeedback:string;feedbackSent:boolean;decisions:Record<string,string>;reviews:Record<string,{judgments:Record<string,string>;feedback:string}>;
}
export const fusionTasks=[{id:'problem',title:'실제 사용자 문제를 한 문장으로 정의',owner:'김민수',stage:'완료',detail:'재학생이 어떤 안내를 찾다가 막히는지 인터뷰로 확인'},{id:'schema',title:'안내문과 출처 데이터 구조 설계',owner:'유송민',stage:'완료',detail:'이전 학기 SQL 지식을 문서 출처 관리에 적용'},{id:'contract',title:'고정 JSON으로 화면·API 계약 확인',owner:'유송민',stage:'진행 중',detail:'백엔드 구축 전에 요청·응답 형식을 합의'},{id:'empty',title:'근거가 없을 때의 화면 만들기',owner:'이서연',stage:'진행 중',detail:'추측 답변 대신 자료 없음과 다음 확인 방법 표시'},{id:'test',title:'일치·미등록·개인정보 질문 검증',owner:'박지훈',stage:'할 일',detail:'성공 사례뿐 아니라 실패와 경계 조건도 기록'},{id:'reflect',title:'새로 배운 개념과 적용 근거 공유',owner:'유송민',stage:'할 일',detail:'힌트를 어떤 판단과 실제 행동으로 옮겼는지 설명'}]
const student:StudentState={...structuredClone(studentInitial),privateMessages:[{author:'유송민',text:'Python은 배웠는데 React 화면과 어떻게 연결할지 모르겠어요.',time:'14:02'},{author:'AI',text:'지금은 도구를 더 고르기보다 입력과 출력부터 합의해 볼까요? 사용자가 보내는 질문과 화면에 필요한 답변·출처를 JSON 예시로 작성하고, 실제 서버 없이 화면에 연결해 보세요.',time:'14:02',level:2}],teamMessages:[{author:'김민수',text:'인터뷰에서는 식당 메뉴보다 장학·시설 안내를 찾는 과정이 더 불편하다고 했어. 우선 공개 안내문 5개로 범위를 좁히자.',time:'13:50'},{author:'이서연',text:'답변 아래 출처와 수정일을 보여주는 화면을 만들고 있어. 자료가 없을 때 상태도 필요해.',time:'14:04'},{author:'유송민',text:'이전 학기 DB 설계를 가져와 문서 ID와 출처를 묶어볼게. API는 고정 응답으로 먼저 맞춰보자.',time:'14:05'}],resources:[{name:'사용자 인터뷰 요약',kind:'팀 문서',body:'재학생 3명 대상 가상 인터뷰\n관찰: 검색어를 바꿔도 안내 위치를 찾기 어려움\n요구: 답과 함께 원문 안내로 돌아갈 수 있어야 함\n다음: 공개 안내문 5개로 먼저 검증',author:'김민수',version:2},{name:'자료 구조 설계',kind:'팀 문서',body:'이전 학기 데이터베이스 지식 연결\ndocument: id, title, body, source, updated_at\nanswer: text, source_ids, status\n출처가 없는 응답은 not_found로 구분한다.',author:'유송민',version:1},{name:'검증 문항과 성공 기준',kind:'검증 기록',body:'1. 등록된 안내 질문 → 출처와 답변을 함께 표시\n2. 자료에 없는 질문 → 답변을 보류\n3. 학번이 포함된 질문 → 식별 정보 없이 기록\n4. 서버 오류 → 재시도 안내\n예시 결과는 실제 사용자 검증과 구분한다.',author:'박지훈',version:1}],checks:[]}
export const initialFusion:FusionData={brief:'AI를 활용해 실제 사용자의 문제를 해결하는 프로그램을 기획하고 제작하세요. 주제·언어·프레임워크·도구는 팀이 선택합니다. 다른 교과나 이전 학기의 지식을 연결하고, 새로 배운 내용을 어디에 적용했는지 근거를 남기세요.',rubric:fusionRubric,plan:{name:'캠퍼스 길잡이',problem:'학교 안내가 흩어져 필요한 정보를 찾기 어렵다.',audience:'학교생활 정보를 찾는 재학생',scope:'공개 안내문 5개에 대해 출처를 보여주는 질의응답 프로토타입',language:'TypeScript + Python',frontend:'React',backend:'FastAPI',tools:'Figma · Git · SQLite',reason:'배운 Python을 API에 활용하고, 웹 수업의 컴포넌트 지식을 화면에 적용한다. 먼저 고정 JSON으로 화면을 검증한 뒤 검색과 생성을 단계적으로 연결한다.'},connections:fusionConnections,completed:['problem','schema'],experiment:false,experimentNote:'',evidence:[{title:'정보 탐색 문제의 범위 정의',detail:'인터뷰 요약에서 안내 검색 실패와 단순한 답변 생성 요구를 구분했습니다. 안내 원문으로 돌아갈 수 있어야 한다는 사용자 조건을 팀과 합의했습니다.',owner:'유송민',source:'사용자 인터뷰 → 데이터 요구 정의',criterion:'문제 정의',time:'13:57'},{title:'요청·응답 계약 초안',detail:'웹 수업에서 배운 요청·응답을 answer, source_ids, status 필드로 표현했습니다. 정상 예시는 합의했으며 자료 없음과 오류 조건은 추가 확인이 필요합니다.',owner:'유송민',source:'이번 학기 · 웹 프로그래밍',criterion:'설계·구현 과정',time:'14:06'},{title:'프런트엔드와 필드 합의',detail:'이서연의 화면 요구와 데이터 구조를 비교해 출처·수정일 필드를 공유했습니다. 아직 응답 오류 상태의 표현은 합의되지 않았습니다.',owner:'유송민',source:'팀 대화 · 공동 설계',criterion:'협업',time:'14:07'},{title:'자료 구조 설계',detail:'이전 학기 테이블·키 개념을 문서 ID와 출처 연결에 적용했습니다.',owner:'유송민',source:'이전 학기 · 데이터베이스',criterion:'지식 연결·전이',time:'14:01'},{title:'인터뷰로 범위 좁히기',detail:'요구를 비교해 공개 안내문 5개로 1차 범위를 정했습니다.',owner:'김민수',source:'다른 교과 · UX·의사소통',criterion:'문제 정의',time:'13:55'}],student,guidance:[{level:2,topic:'요청·응답 계약을 작은 실험으로 나누기',time:'14:02'}],request:'자료가 없는 질문을 처리하는 방법과 검증 기준을 함께 점검받고 싶습니다.',teacherFeedback:'',feedbackSent:false,decisions:{},reviews:{}}
export function readFusion():FusionData{try{const d=JSON.parse(localStorage.getItem(fusionStorage)||'null');if(d?.plan&&d.student&&Array.isArray(d.connections)&&Array.isArray(d.evidence))return {...structuredClone(initialFusion),...d}}catch{/* Independent demo workspace. */}return structuredClone(initialFusion)}
export function fusionReply(question:string){
 if(/개인정보|학번|보안/.test(question))return{level:3,topic:'정보 윤리 → 질문 로그 설계',text:'정보 윤리에서 배운 최소 수집 원칙을 적용해 볼까요? 질문에 학번이 있어야 답할 수 있는지 먼저 구분하세요. 없어도 된다면 저장 전에 지우는 규칙을 정하고, 가짜 학번을 넣은 입력으로 무엇이 남는지 확인해 보세요.'}
 if(/언어|프레임워크|React|Python|도구|기술/i.test(question))return{level:2,topic:'배운 기술과 새로 필요한 기능 비교',text:'만들 기능, 이미 할 수 있는 것, 새로 필요한 것을 세 칸으로 나눠 보세요. 화면·데이터·AI 처리 중 어느 부분이 가장 불확실한가요? 두 기술 후보를 학습 부담과 검증 가능한 최소 기능으로 비교하고 선택 이유를 팀 기획에 남겨보세요.'}
 if(/출처|없는|환각|근거|검색/.test(question))return{level:3,topic:'데이터베이스·정보 탐색 → 근거 검증',text:'답변 생성과 자료 검색을 분리해서 생각해 볼까요? 먼저 “질문에 해당하는 자료가 있는가”를 확인하고, 없으면 생성을 멈추는 규칙을 만들어 보세요. 등록된 질문과 미등록 질문을 같은 조건에서 비교하면 어떤 결과가 나와야 하나요?'}
 if(/API|연결|JSON|서버|실행/i.test(question))return{level:4,topic:'웹·프로그래밍 → 요청·응답 실험',text:'실제 서버를 붙이기 전에 { answer, sources, status } 형태의 고정 JSON을 화면에 넣어보세요. 정상·자료 없음·오류 응답을 각각 만들어 표시가 달라지는지 확인하세요. 그 다음 같은 형식을 반환하는 작은 API 하나를 연결하면, 화면과 서버 중 어디에서 막혔는지 나눠 볼 수 있습니다.'}
 return{level:1,topic:'문제와 다음 확인 행동 구체화',text:'누가 어떤 상황에서 겪는 문제인가요? 지금 알고 있는 사실과 아직 확인하지 못한 가정을 나눠 적어보세요. 기존 교과에서 써본 개념 중 이 가정을 작게 시험하는 데 활용할 수 있는 것은 무엇인가요?'}
}
