import { ProgressRing } from './TeachingCharts'
type Team = { id: number; progress: number; status: string; stage: string; recent: string }
const stages = ['문제 이해', '원인·요구 분석', '실행·수정', '결과 검증']
const currentStage = (t:Team) => /검증/.test(t.stage) ? 3 : /수정|구성/.test(t.stage) ? 2 : 1
export function MonitoringMap({ teams, selected, onSelect }: { teams: Team[]; selected:number; onSelect:(id:number)=>void }) {
  return <div className="stage-map-scroll"><div className="stage-map" aria-label="팀별 수행 단계 지도"><div className="stage-map-head"><span>팀 / 진행률</span>{stages.map(s=><span key={s}>{s}</span>)}<span>상태 · 최근 활동</span></div>{teams.map(t=><button className={`stage-map-row ${selected===t.id?'selected':''}`} aria-label={`${t.id}팀 ${t.progress}% ${t.stage} ${t.status} ${t.recent}`} aria-pressed={selected===t.id} key={t.id} onClick={()=>onSelect(t.id)}><span className="map-team"><strong>{t.id}팀</strong><ProgressRing value={t.progress} label={`${t.id}팀 진행률`} tone={t.status==='지연'?'rose':t.status==='확인 필요'?'yellow':t.status==='승인 대기'?'lavender':'mint'} /></span>{stages.map((s,i)=><span key={s} className={`stage-cell ${i<currentStage(t)?'done':i===currentStage(t)?t.status==='지연'?'stalled':t.status==='확인 필요'?'attention':t.status==='승인 대기'?'approval':'current':'upcoming'}`} aria-label={`${s} ${i<currentStage(t)?'진행 기록 있음':i===currentStage(t)?'현재 단계':'예정'}`}><span>{i<currentStage(t)?'완료':i===currentStage(t)?t.status==='지연'?'지연':t.status==='확인 필요'?'확인':t.status==='승인 대기'?'승인':'진행':'—'}</span></span>)}<span className="map-status"><strong>{t.status}</strong><small>{t.recent}</small></span></button>)}</div><div className="map-legend"><span><i className="mint" />진행 기록 있음</span><span><i className="yellow" />확인 필요</span><span><i className="rose" />지연</span><span><i className="lavender" />승인 대기</span></div></div>
}
export function StageDistribution({ teams }: { teams:Team[] }) {
  return <div className="stage-distribution"><h3>현재 단계별 팀 분포</h3><div className="distribution-bar" role="img" aria-label={stages.map((s,i)=>`${s} ${teams.filter(t=>currentStage(t)===i).length}팀`).join(', ')}>{stages.map((s,i)=> {const n=teams.filter(t=>currentStage(t)===i).length;return n>0?<span key={s} className={`distribution-${i}`} style={{flex:n}}>{s} {n}</span>:null})}</div><p>진행률은 시연용 과제 진행 상태이며, 이해도나 평가 점수가 아닙니다.</p></div>
}
