import { useEffect, useRef, useState, type ReactNode } from 'react'
import { ChevronDown, Check, UserRound, BookOpen, GraduationCap } from 'lucide-react'
export function SidebarDropdown({label,children,trigger,up=false}:{label:string;children:(close:()=>void)=>ReactNode;trigger:ReactNode;up?:boolean}) {
  const [open,setOpen]=useState(false),root=useRef<HTMLDivElement>(null)
  useEffect(()=>{if(!open)return;function outside(e:PointerEvent){if(!root.current?.contains(e.target as Node))setOpen(false)}function escape(e:KeyboardEvent){if(e.key==='Escape'){setOpen(false);root.current?.querySelector('button')?.focus()}}document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape)}},[open])
  return <div ref={root} className={`sidebar-dropdown ${up?'profile-dropdown':''}`}><button className="sidebar-dropdown-trigger" aria-label={label} aria-expanded={open} onClick={()=>setOpen(!open)}>{trigger}<ChevronDown size={17} className={open?'rotated':''}/></button>{open&&<div className={`sidebar-dropdown-panel ${up?'opens-up':''}`} role="region" aria-label={label}><div className="dropdown-heading">{label}</div>{children(()=>setOpen(false))}</div>}</div>
}
export function ProfileSwitch({student,onSwitch,workspace="network"}:{student:boolean;onSwitch:()=>void;workspace?:"network"|"fusion"}) {return <SidebarDropdown label="프로필 전환" up trigger={<><span className="dropdown-avatar"><UserRound size={21}/></span><span className="dropdown-identity"><strong>{student?'유송민':'강병준'}</strong><small>{student?'학생 · 1팀':'교수자 · 한국 폴리텍'}</small></span></>}>{close=><>{[false,true].map(s=><button key={String(s)} className="dropdown-option" aria-pressed={s===student} onClick={()=>{close();if(s!==student)onSwitch()}}><UserRound size={20}/><span><strong>{s?'유송민':'강병준'}</strong><small>{s?`학생 · ${workspace==='fusion'?'융합 프로젝트':'네트워크 실습'} 1팀`:'교수자 · 한국 폴리텍'}</small></span>{s===student&&<Check size={17}/>}</button>)}<p className="dropdown-note">시연용 프로필</p></>}</SidebarDropdown>}
export function WorkspaceSwitch({onSelect,active='network',student=true}:{onSelect:(id:'network'|'fusion')=>void;active?:'network'|'fusion';student?:boolean}) {return <SidebarDropdown label="워크스페이스 전환" trigger={<><BookOpen size={20}/><span className="dropdown-identity"><strong>{active==='network'?'2학년 네트워크 실습':'융합 팀 프로젝트'}</strong><small>2026년 2학기 · {student?'1팀':'교수자'}</small></span></>}>{close=><>{(['network','fusion'] as const).map(id=><button key={id} className="dropdown-option" aria-pressed={id===active} onClick={()=>{close();onSelect(id)}}>{id==='network'?<BookOpen size={20}/>:<GraduationCap size={20}/>}<span><strong>{id==='network'?'2학년 네트워크 실습':'융합 팀 프로젝트'}</strong><small>{id===active?'현재 워크스페이스':id==='fusion'?'교과를 연결하는 열린 프로젝트':'네트워크 장애 진단 실습'}</small></span>{id===active&&<Check size={17}/>}</button>)}</>}</SidebarDropdown>}
