import { useState } from 'react'
import { useWorkspace } from './WorkspaceContext'
export function ProjectSimulation(){
 const {scenario:s,data,setData}=useWorkspace()
 const [target,setTarget]=useState(s.nodes[0][0]),[command,setCommand]=useState(''),[rules,setRules]=useState([false,false]),[checks,setChecks]=useState<Record<string,boolean>>({}),[lines,setLines]=useState<string[]>(['TRACE 모의 실행 환경 · 실제 장비·코드·API에는 연결되지 않습니다.']),[note,setNote]=useState(data.experimentNote),[notice,setNotice]=useState('')
 const config=s.id==='network'?{labels:['수정 전 실패 결과를 비교 기준으로 사용','반대 방향의 결과까지 확인'],conditions:['경로 수정','본사 → 지사','지사 → 본사'],commands:['show ip route','show ip interface brief','ip route 192.168.10.0 255.255.255.0 10.0.0.1','ping 192.168.20.10','ping 192.168.10.10'],placeholder:'예: show ip route',title:'양방향 복구 검증'}:{labels:['근거 자료가 없으면 답변 보류','질문 로그에서 학번 가리기'],conditions:['등록된 질문','자료에 없는 질문','개인정보 포함 질문'],commands:['GET /schema','TEST registered','TEST unknown','TEST privacy','GET /status'],placeholder:'예: TEST unknown',title:'근거와 개인정보 경계 조건 검증'}
 const passed=config.conditions.every(c=>checks[c])&&rules.every(Boolean)
 function run(value=command){
  const input=value.trim().replace(/\s+/g,' ');if(!input)return
  let output='지원하는 명령·요청을 아래 목록에서 확인해 주세요.',nextChecks={...checks},student={...data.student}
  if(s.id==='network'){
   if(input==='show ip route')output=target==='R1'?'S 192.168.20.0/24 via 10.0.0.2':target==='R2'?`S 192.168.10.0/24 via ${student.routeFixed?'10.0.0.1':'10.0.0.9'}`:'라우터를 선택해 경로를 확인하세요.'
   else if(input==='show ip interface brief')output='R1: 10.0.0.1 up/up\nR2: 10.0.0.2 up/up'
   else if(input.startsWith('ip route ')){if(target==='R2'&&input===config.commands[2]){student={...student,routeFixed:true,forward:false,reverse:false};nextChecks={'경로 수정':true};output='R2 정적 경로 수정됨. 두 PC의 양방향 결과를 확인하세요.'}else output='R2와 실제 인접 주소를 확인하세요. 설정은 변경되지 않았습니다.'}
   else if(input.startsWith('ping ')){const forward=target==='PC-A'&&input==='ping 192.168.20.10',reverse=target==='PC-B'&&input==='ping 192.168.10.10';if(!forward&&!reverse)output='PC-A에서 지사 PC, PC-B에서 본사 PC를 확인하세요.';else if(!student.routeFixed)output='Request timed out. Sent = 4, Received = 0 (100% loss)';else{student={...student,forward:student.forward||forward,reverse:student.reverse||reverse};nextChecks[forward?'본사 → 지사':'지사 → 본사']=true;nextChecks['경로 수정']=true;output='Reply received · 4/4 · 0% loss'}}
  }else{
   if(input==='GET /schema')output='{ answer, sources, status } · 문서 ID로 출처 연결'
   if(input==='GET /status')output=`답변 보류 규칙: ${rules[0]?'설정':'미설정'} / 식별 정보 가림: ${rules[1]?'설정':'미설정'}`
   const i=['TEST registered','TEST unknown','TEST privacy'].indexOf(input)
   if(i>=0){const ok=i===0||rules[i-1];nextChecks[config.conditions[i]]=ok;output=i===0?'도서관 운영: 평일 09:00–18:00 · 가상 안내문 D01':i===1?ok?'자료 없음 · 추측 답변 중단. 담당 부서 확인 안내':'보완 필요 · 자료가 없는 질문에 근거 없는 답변을 생성함':ok?'저장 기록: [학번 가림] 학생의 이용 문의':'보완 필요 · 가짜 학번 20260001이 로그에 남음'}
  }
  setChecks(nextChecks);setLines([...lines,`${target}> ${input}`,output].slice(-40));setCommand('');setData({...data,student})
 }
 function publish(){if(!passed||!note.trim())return;const detail=`${config.conditions.join(' / ')} 확인. ${note.trim()}`;const resource={id:'project-verification',name:config.title,kind:'Learning Evidence',body:detail,author:'유송민',version:1};const found=data.student.resources.findIndex(r=>r.id==='project-verification');const resources=[...data.student.resources];if(found<0)resources.push(resource);else resources[found]={...resources[found],body:detail,version:(resources[found].version||1)+1};setData({...data,experiment:true,experimentNote:note,completed:[...new Set([...data.completed,'test'])],evidence:[...data.evidence.filter(e=>e.source!=='프로젝트 작업실 · 모의 검증'),{title:config.title,detail,owner:'유송민',source:'프로젝트 작업실 · 모의 검증',criterion:'검증',time:'방금'}],student:{...data.student,submitted:true,resources,teamMessages:[...data.student.teamMessages,{author:'유송민',text:`${config.title}과 판단 근거를 팀 자료에 공유했습니다.`,time:'방금'}]}});setNotice('검증 결과를 팀 자료와 나의 학습 기록에 남겼습니다.')}
 return <><section className="panel"><div className="section-heading"><h2>실행 환경과 검증</h2><span className="teach-badge yellow">모의 실행</span></div><p className="section-note">{data.plan.scope}</p><div className="network-topology" aria-label="프로젝트 구성도">{s.nodes.map(([name,info])=><div key={name}><span>{name}</span><small>{info}</small></div>)}</div><div className="fusion-prototype"><div><h3>검증 조건</h3>{config.labels.map((label,i)=><label className="student-learning-check" key={label}><input type="checkbox" checked={rules[i]} onChange={e=>{setRules(rules.map((v,j)=>i===j?e.target.checked:v));setChecks({});setNotice('조건이 바뀌었습니다. 결과를 다시 확인해 주세요.')}}/>{label}</label>)}<label className="field">실행 대상<select aria-label="실행 대상" value={target} onChange={e=>setTarget(e.target.value)}>{s.nodes.map(n=><option key={n[0]}>{n[0]}</option>)}</select></label><p className="course-demo-note">{s.moduleEvidence} · 시연용으로 정의된 요청만 처리합니다.</p></div><div><pre role="log" aria-label="모의 실행 기록" className="student-console">{lines.join('\n')}</pre><form className="console-form" onSubmit={e=>{e.preventDefault();run()}}><label htmlFor="project-command">명령·요청</label><input id="project-command" placeholder={config.placeholder} value={command} onChange={e=>setCommand(e.target.value)}/><button className="button primary">실행</button></form></div></div><div className="command-shortcuts">{config.commands.map(c=><button className="text-button" key={c} onClick={()=>run(c)}>{c}</button>)}</div><div className="fusion-test-checks">{config.conditions.map(c=><span key={c} className={checks[c]?'passed':''}>{checks[c]===undefined?'미확인':checks[c]?'확인 완료':'보완 필요'} · {c}</span>)}</div></section><section className="panel"><div className="section-heading"><h2>결과 기록과 공유</h2><span className="count-label">수행 결과 + 나의 설명</span></div><label className="field">어떤 근거로 판단했고, 무엇을 더 확인해야 하나요?<textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder={s.guidance}/></label><p className="course-demo-note">세 가지 결과와 검증 조건을 확인한 뒤 판단 근거를 남기세요. 외부에서 수행한 실습도 팀 자료에 파일과 설명을 첨부할 수 있습니다.</p><button className="button primary" disabled={!passed||!note.trim()} onClick={publish}>검증 근거 팀에 공유</button>{notice&&<p role="status">{notice}</p>}</section></>
}
