import { initialAssignment, type Assignment } from './assignment'
import { defaultCourse, type Course } from './course'
import { teachingTeams, studentEvidence, type Evidence } from './evidence'
import { initialFusion, fusionReply, fusionTasks, type FusionData } from './fusion'
import { studentInitial, guidanceReply, selectGuidanceLevel } from './student'
export type WorkspaceId='network'|'fusion'
export type ProjectData=FusionData
export const workspaceKey=(id:WorkspaceId,key:string)=>id==='network'?key:`fusion-${key}`
const fusionAssignment:Assignment={...structuredClone(initialAssignment),title:'AI를 활용한 프로그램 기획·제작',description:initialFusion.brief,goals:['실제 사용자 문제를 정의하고 필요한 지식을 연결한다.','도구 선택의 근거를 설명하고 작은 실험으로 가설을 검증한다.','다른 교과와 이전 학기 개념을 적용한 수행 근거를 남긴다.'],requirements:['사용자의 문제와 최소 제작 범위를 구체적으로 정의한다.','언어·프레임워크·도구 후보를 비교하고 선택 이유를 설명한다.','교과 지식을 적용하고 정상·실패 조건의 검증 결과를 남긴다.'],outputs:[{name:'문제 정의와 기술 선택서',format:'PDF',required:'필수'},{name:'프로토타입 및 검증 기록',format:'코드',required:'필수'}],environment:{kind:'workspace',template:'근거 기반 응답 검증',url:'',instructions:''},criteria:[{name:'문제 이해',weight:20},{name:'지식 연결·해결 과정',weight:30},{name:'검증',weight:20},{name:'산출물',weight:20},{name:'협업',weight:10}],situation:'자료에 없는 질문에도 프로그램이 답변을 생성합니다.',manualGuidance:'자료가 있는 질문과 없는 질문의 처리 결과를 비교하고, 답변을 보류해야 하는 조건을 설명해 보세요.'}
const fusionCourse:Course={...structuredClone(defaultCourse),name:'융합 팀 프로젝트',students:'융합 프로젝트 A반 · 24명',description:initialFusion.brief,goals:fusionAssignment.goals,standards:['사용자 요구와 최소 제작 범위를 근거로 정의한다.','이전 학기·다른 교과의 개념을 새 설계에 적용한다.','정상·실패·경계 조건을 비교하여 검증한다.'],ncs:['응용 소프트웨어 개발 · 시연용 능력단위','정보서비스 기획 · 시연용 능력단위'],criteria:fusionAssignment.criteria,curriculum:['문제 탐색','사용자 인터뷰','선행 지식 점검','아이디어 비교','기술·도구 선택','데이터 설계','작은 프로토타입','중간 프로젝트 점검','API·화면 통합','경계 조건 처리','사용자 검증','정보 윤리','교과 지식 전이','팀 프로젝트 개선','산출물 검토','최종 발표와 성찰'],documents:[{name:'융합프로젝트 수업계획서.pdf',type:'수업계획',area:'목표 · 일정',updated:'2026-09-01'},{name:'융합프로젝트 평가계획.pdf',type:'평가',area:'평가 기준',updated:'2026-09-01'}]}
const networkConnections=[
 {name:'네트워크 기초',source:'이전 학기',known:'IP 주소와 서브넷',need:'장애 범위를 주소와 경로로 구분',action:'본사·지사·라우터 연결 대역을 표로 비교',status:'적용 중'},
 {name:'라우팅 실습',source:'이번 학기',known:'정적 경로의 목적지와 다음 홉',need:'요청 경로와 반환 경로를 함께 진단',action:'두 라우터의 경로와 인터페이스 비교',status:'작은 실험'},
 {name:'문제해결 · 의사소통',source:'다른 교과',known:'관찰과 가설 구분',need:'원인 후보를 증거로 좁히기',action:'정상 구간·실패 구간을 팀에 설명',status:'근거 확보'},
 {name:'진단 도구',source:'새로 탐색',known:'기본 Ping 실행',need:'명령 결과를 경로·설정과 연결',action:'수정 전후와 양방향 결과를 비교',status:'지도 필요'},
 {name:'기술 문서 작성',source:'다른 교과',known:'결과와 근거 정리',need:'검증의 범위와 한계를 설명',action:'결과 파일과 학생 설명을 함께 기록',status:'확인 필요'}]
const networkProject:ProjectData={...structuredClone(initialFusion),brief:initialAssignment.description,rubric:initialAssignment.criteria,plan:{name:'본사·지사 연결 복구',audience:'교내 실습실 사용자',problem:'본사 PC와 지사 PC 사이에 통신이 되지 않는다.',scope:'R1·R2의 정적 경로 진단과 두 PC의 양방향 검증',language:'장비 CLI',frontend:'가상 네트워크 구성도',backend:'정적 라우팅',tools:'Ping · 경로 조회 · 팀 문서',reason:'이전 학기의 주소 체계와 이번 학기의 라우팅 지식을 연결한다. 설정을 한 항목씩 비교하고 수정한 뒤 양방향 결과로 확인한다.'},connections:networkConnections,student:structuredClone(studentInitial),evidence:[{title:'장애 구간의 첫 가설',detail:'게이트웨이까지 정상이고 지사 PC 응답은 없습니다. 전체 초기화 대신 두 라우터의 경로를 비교하겠습니다.',owner:'유송민',source:'관찰 → 원인 후보',criterion:'문제 이해',time:'14:03'},{title:'주소와 경로 비교',detail:'이전 학기 주소 대역 지식을 사용해 다음 홉과 실제 연결을 비교했습니다.',owner:'유송민',source:'이전 학기 · 네트워크 기초',criterion:'지식 연결·해결 과정',time:'14:08'}],guidance:[{level:1,topic:'관찰한 구간과 다음 확인 지점 구분',time:'14:03'}],request:'반환 경로를 확인한 뒤 어떤 조건으로 검증해야 하는지 함께 점검받고 싶습니다.',completed:['problem','schema'],experiment:false,experimentNote:'',teacherFeedback:'',feedbackSent:false,decisions:{},reviews:{}}
const networkTasks=fusionTasks.map((t,i)=>({...t,title:['장애 현상과 영향 범위 정의','주소와 경로 데이터 비교','수정할 다음 홉과 근거 합의','수정 전후 상태 기록','양방향 통신 결과 검증','적용한 개념과 판단 근거 공유'][i],detail:['어느 구간부터 실패하는지 관찰 결과를 정리','IP·서브넷·정적 경로 지식을 적용','원인 가설과 변경할 항목을 연결','팀원이 같은 조건으로 확인할 자료 작성','본사→지사 및 지사→본사 결과를 비교','판단·수정·검증에서 무엇을 배웠는지 설명'][i]}))
const fusionTeamNames=['캠퍼스 길잡이','공유물품 연결소','학습 회고 노트','급식 수요 예측','접근성 안내 도우미','에너지 사용 리포트']
const fusionTeamKnowledge=['데이터베이스 · 웹 · 정보 윤리','수학 · 데이터베이스 · 사용자 조사','교육학 · 통계 · 웹','확률과 통계 · 데이터 분석','UX · 접근성 · 프로그래밍','물리 · 통계 · 시각화']
export const scenarios={
 network:{id:'network' as WorkspaceId,course:defaultCourse,assignment:initialAssignment,project:networkProject,tasks:networkTasks,roles:['네트워크 설정·검증','장애 원인 분석','진단 도구 운영','과정 기록·공유'],studentRole:'네트워크 설정·검증',projectNames:['네트워크 장애 진단','VLAN 통신 검증'],secondaryTitle:'VLAN 분리 및 부서 간 통신 검증',templates:['정적 라우팅 장애 진단','VLAN 소속 오류 진단'],moduleEvidence:'명령 실행 · 설정 변경 · 통신 검증 결과',nodes:[['PC-A','192.168.10.10'],['R1','10.0.0.1'],['R2','10.0.0.2'],['PC-B','192.168.20.10']],needTitle:'설정 변경과 복구 확인을 어떻게 구분할까?',need:'주소와 경로는 알고 있지만, 반환 경로와 양방향 검증을 함께 확인해야 합니다.',previousGap:'지난 과제에서는 한 방향만 검증했어요. 이번에는 수정 전후·반대 방향·같은 조건을 함께 확인하세요.',approvalSituation:'다른 대역의 단말에서만 통신이 실패하는 상황',approvalReason:'현재 결과는 기록된 두 단말에 한정됩니다.',guidance:'설정을 바꾸기 전과 후에 무엇이 달라졌나요? 원인 후보를 하나 정하고, 이를 확인할 검증 방법을 설명해 보세요.',prompts:['어느 구간부터 확인할까요?','왜 양방향으로 검증해야 하나요?','어떤 명령으로 경로를 확인하나요?'],concepts:['주소 대역과 통신 경로','양방향 라우팅'],strength:['관찰한 사실로 원인 범위를 좁힘','정상 구간과 실패 구간을 나눠 보고, 실제 설정을 가설과 비교했습니다.'],gap:['진단 계획만 있고 실제 수정 자료는 없습니다. 가설과 수정안의 연결을 확인해 주세요.','검증 계획은 있지만 실행 결과가 없습니다. 양방향 통신 결과를 확인해 주세요.','두 단말의 결과는 있습니다. 다른 대역에서도 성립하는지 자기 설명을 확인해 주세요.'],teams:teachingTeams.map(t=>({...t,name:`${t.id}팀 네트워크 복구`,knowledge:'주소 체계 · 라우팅 · 기술 문서',tools:'장비 CLI · Ping · 경로 조회'})),reply:(q:string,verified:boolean)=>{const level=selectGuidanceLevel(q,verified);return{level,topic:['관찰한 사실 정리','요청·반환 경로 비교','통신 성립 조건 설명','진단 도구와 검증 방법'][level-1],text:guidanceReply(level,verified)}}},
 fusion:{id:'fusion' as WorkspaceId,course:fusionCourse,assignment:fusionAssignment,project:{...structuredClone(initialFusion),rubric:fusionAssignment.criteria},tasks:fusionTasks,roles:['API·데이터 연결','사용자 문제 분석','프로토타입 검증','과정 기록·공유'],studentRole:'API·데이터 연결',projectNames:['AI 프로그램 기획·제작','사용자 요구와 기술 비교'],secondaryTitle:'사용자 요구 분석과 기술 선택',templates:['근거 기반 응답 검증','사용자 입력 경계 조건 검증'],moduleEvidence:'요청 실행 · 응답 규칙 변경 · 경계 조건 검증',nodes:[['질문 입력','사용자 요구'],['화면','React'],['API','Python · FastAPI'],['자료','문서·출처 DB']],needTitle:'검색·생성·검증을 어떻게 나눌까?',need:'Python 문법은 알고 있지만, 화면과 API 연결 및 근거 없는 응답 처리에는 새 학습이 필요합니다.',previousGap:'지난 웹 과제에서는 정상 화면만 확인했어요. 이번에는 자료 없음·오류·개인정보 조건을 명시하고 처리 이유를 설명하세요.',approvalSituation:'자료에 없는 질문과 개인정보가 포함된 질문을 추가하는 상황',approvalReason:'정상 응답만으로 다른 입력 조건의 동작을 보장할 수 없습니다.',guidance:'현재 알고 있는 개념과 새로 필요한 개념을 나누고, 실제 API 없이 확인할 수 있는 가장 작은 실험을 설명해 보세요.',prompts:['배운 Python과 새 프레임워크를 어떻게 고를까요?','자료에 없는 질문은 어떻게 처리하나요?','화면과 API를 어떻게 연결하나요?'],concepts:['사용자 요구와 자료 출처','요청·응답과 데이터 구조'],strength:['이전 교과의 개념을 새 설계에 연결함','자료 구조와 사용자 요구를 비교하고, 새 프로그램에 필요한 조건을 설명했습니다.'],gap:['기술 비교 계획만 있고 적용 자료는 없습니다. 작은 실험의 범위를 확인해 주세요.','검증 계획은 있지만 실행 결과가 없습니다. 정상·미등록·개인정보 조건을 확인해 주세요.','모의 조건의 결과는 있습니다. 실제 사용자와 API에서도 성립하는지 확인해 주세요.'],teams:teachingTeams.map((t,i)=>({...t,name:fusionTeamNames[i],knowledge:fusionTeamKnowledge[i],tools:['TypeScript · React · Python · FastAPI','Python · Streamlit · SQLite','TypeScript · React · Node.js','Python · 데이터 분석 도구','웹 · 음성 안내 · UX 도구','Python · 시각화 도구'][i],summary:['출처와 답변의 연결을 확인했습니다. 자료 없는 질문과 식별 정보 처리 범위를 더 확인합니다.','기술 후보를 비교했지만 기준 모델의 실행 결과가 없습니다. 최적화 전에 수량 조건 하나로 시험할 수 있는지 확인합니다.','기본 회고 질문을 구현했습니다. 새로운 입력 조건을 추가하는 상황 제안이 승인 대기입니다.','데이터 표본 비교 후 수행이 멈췄습니다. 배운 통계 개념을 예측 조건으로 옮기는 데 어려움이 있는지 확인합니다.','사용자 조건별 동작 결과를 비교했습니다. 접근성 확인 범위를 자기 설명으로 정리합니다.','소비 데이터 정규화 규칙을 바꾸고 검증 계획을 공유했습니다. 후속 비교 결과를 기다립니다.'][i],reasons:[i===1?'18분간 후속 수행 기록 없음':i===3?'32분간 새 수행 기록 없음':'설계·수행 근거 비교 필요',i===1||i===3?'작은 실험과 검증 결과 미수집':'기존 지식의 적용 범위와 한계 확인']})),reply:(q:string,_verified:boolean)=>fusionReply(q)}
}
export type Scenario=typeof scenarios.network
export function readProject(id:WorkspaceId):ProjectData{
 const base=structuredClone(scenarios[id].project)
 try{const current=JSON.parse(localStorage.getItem(`trace-project-${id}-v2`)||'null');if(current?.plan&&current.student&&Array.isArray(current.evidence))return {...base,...current}
 const legacy=JSON.parse(localStorage.getItem(id==='network'?'trace-student-yusongmin-v1':'trace-fusion-workspace-v1')||'null');if(legacy)return id==='network'?{...base,student:{...base.student,...legacy}}:{...base,...legacy}
 }catch{/* Local scenario fallback. */}return base
}
export function scenarioEvidence(s:Scenario,name:string,role:string,team:number,alternate:boolean,project?:ProjectData){
 const data=studentEvidence(name,role,team,alternate)
 if(s.id==='fusion'){
 const topic=s.teams[team-1].name
 const korean=['사용자 문제와 범위 가설','기존 지식과 새 요구 비교','최소 구현과 선택 근거','경계 조건의 결과 검증','다음 검증 계획과 팀 공유']
 const raw=[`${topic}: 사용자 문제와 최소 범위를 구분. 실제 요구를 비교한 뒤 기능을 하나로 좁힘.`,`연결 교과: ${s.teams[team-1].knowledge}\n알고 있는 개념과 새로 필요한 조건을 표로 비교함.`,`선택한 도구: ${s.teams[team-1].tools}\n변경 전: 정상 조건만 고려\n변경 후: 입력·출력 계약과 실패 조건을 분리`,'정상 질문: 출처와 답변 표시\n미등록 질문: 답변 보류\n식별 정보 입력: 기록 제외\n모의 조건의 결과이며 실제 서비스 검증은 남음','다음 조건을 팀 문서에 공유. 지원 힌트를 그대로 옮기지 않고 실제 요구와 비교하여 판단함.']
 data.evidence=data.evidence.map(e=>({...e,title:korean[Number(e.id.slice(1))-1],source:e.shared?'팀 공유 · 설계 자료':'학생 수행 · 프로젝트 기록',goal:'기존 지식을 새로운 문제에 적용하고 근거로 설명하기',raw:raw[Number(e.id.slice(1))-1],explanation:'배운 개념과 이번 프로그램의 요구를 비교했습니다. 아직 확인하지 못한 조건은 다음 실험으로 남겼습니다.',interpretation:'선택한 개념과 실제 수행을 연결한 기록이 있습니다. 다른 조건에 대한 이해는 추가 질문으로 확인합니다.',limitation:e.shared?'팀 자료를 해석한 기록입니다. 직접 수행 여부는 학생 설명과 함께 확인하세요.':'기록된 예시 조건만으로 전체 프로그램의 품질을 확정하지 않습니다.'}))
 data.guidance=data.guidance.map((g,i)=>({...g,reason:['문제 범위를 정하기 어려움','배운 기술과 새 조건을 연결하지 못함','구현과 검증을 혼동할 가능성','작은 실험 방법의 구체화 필요','학생이 다음 확인을 직접 선택함'][i],support:['관찰한 사용자 요구를 구분하는 확인 질문','기존 지식과 필요한 기능을 비교하도록 탐색 안내','검색과 생성·검증의 역할을 구분하는 개념 힌트','고정 응답과 경계 입력을 비교하는 도구 힌트','선택 이유와 다음 확인을 스스로 설명하도록 질문'][i],response:i===data.guidance.length-1?'선택 근거와 다음 수행을 설명함':'지원 내용을 실제 요구와 비교하고 계획에 반영함'}))
 }
 if(name==='유송민'&&project){
 const personal=project.evidence.filter(e=>e.owner===name)
 const used=new Set<string>()
 const actual:Evidence[]=personal.map((e,i)=>{const stage=/검증|성찰/.test(e.criterion)?3:/문제/.test(e.criterion)?0:/지식|자료|데이터/.test(e.title+' '+e.criterion)?1:2;const candidate='E0'+(stage+1);const id=used.has(candidate)?'P'+(i+1):candidate;used.add(id);return{id,stage,title:e.title,time:e.time,source:e.source,goal:e.criterion,raw:e.detail,explanation:e.detail,interpretation:'학생이 저장한 수행 설명입니다. 실제 결과와 선택 이유를 함께 대조해 주세요.',limitation:'브라우저에 저장된 시연 기록입니다. 자기 보고만으로 이해도를 확정하지 않습니다.'}})
 actual.push({id:'E05',stage:2,title:'다음 수행 계획과 지도 요청',time:'현재',source:'학생 공유 · 지도 요청',goal:'다음 수행과 확인할 조건 설명',raw:project.request||'아직 공유한 요청이 없습니다.',explanation:project.request||'추가 기록 필요',interpretation:'공유한 계획이며 수행 완료를 뜻하지 않습니다.',limitation:'계획과 실행 결과를 구분해 확인합니다.'})
 const guidance=project.guidance.map(g=>({time:g.time,level:g.level,reason:g.topic,support:['확인 질문','탐색 범위','개념 힌트','도구 활용 힌트'][g.level-1],response:project.experiment?'후속 검증 기록 있음 · 지원과의 연결은 교수자 확인 필요':'후속 수행 설명과 실제 결과를 함께 확인하세요.',evidence:project.experiment?'E04':actual[0].id}))
 return {...data,incomplete:!project.experiment,hasModification:actual.some(e=>e.stage===2&&e.id!=='E05'),evidence:actual,guidance:guidance.length?guidance:[{time:'현재',level:1,reason:'아직 지원 기록이 없습니다.',support:'지원 대기',response:'후속 기록 없음',evidence:actual[0].id}]}
 }
 return data
}
