import {useState,useRef,useEffect,type ReactNode} from 'react'
import {Menu,ArrowRight,Check,Link2,Files} from 'lucide-react'
import {WorkspaceSidebar} from './WorkspaceSidebar'
import {studentNavigation} from './navigation'
import {useWorkspace,useWorkspaceUi} from './WorkspaceContext'
import {ProgressRing} from './TeachingCharts'
import {TeamDocuments} from './TeamDocuments'
import {ProjectSimulation} from './ProjectSimulation'
import {KnowledgeConnections} from './KnowledgeConnections'
import type {FusionEvidence} from './fusion'
import './student.css'
import './fusion.css'
function Panel({title,children,action}:{title:string;children:ReactNode;action?:ReactNode}){return <section className="panel"><div className="section-heading"><h2>{title}</h2>{action}</div>{children}</section>}
const phases=['문제 이해','계획·설계','실행·수정','결과 검증','근거 공유']
export function StudentWorkspace({onInstructor,view,onView}:{onInstructor:()=>void;view:string;onView:(v:string)=>void}){
 const {scenario:s,data,setData}=useWorkspace()
 const {tab,setTab}=useWorkspaceUi()
 const [drawer,setDrawer]=useState(false),[collapsed,setCollapsed]=useState(false),[plan,setPlan]=useState(data.plan),[text,setText]=useState(''),[request,setRequest]=useState(data.request),[notice,setNotice]=useState(''),[resource,setResource]=useState<number|null>(null),[detail,setDetail]=useState<FusionEvidence|null>(null),[task,setTask]=useState('contract'),[workNote,setWorkNote]=useState('')
 const dialog=useRef<HTMLDialogElement>(null),log=useRef<HTMLDivElement>(null)
 useEffect(()=>{if(log.current)log.current.scrollTop=log.current.scrollHeight},[view,data.student.teamMessages.length,data.student.privateMessages.length])
 const progress=Math.round(data.completed.length/s.tasks.length*100),phase=data.completed.includes('reflect')?4:data.experiment?3:2
 const members=[['유송민',s.studentRole,'작업과 판단 근거 정리'],['김민준',s.roles[1],'문제와 요구 조건 비교'],['윤서준',s.roles[2],'실행 결과 교차 확인'],['장시우',s.roles[3],'팀 자료와 산출물 정리']]
 function go(v:string){setText('');setNotice('');setDrawer(false);onView(v);window.scrollTo(0,0)}
 function evidence(e:FusionEvidence){setDetail(e);dialog.current?.showModal()}
 function savePlan(){if(Object.values(plan).some(v=>!v.trim())){setNotice('기획 항목과 선택 이유를 모두 입력해 주세요.');return}setData({...data,plan,evidence:[...data.evidence,{title:'계획과 도구 선택 근거',detail:plan.reason,owner:'유송민',criterion:'해결 과정',source:'기획·기술 선택',time:'방금'}]});setNotice('팀 기획과 선택 이유를 저장했습니다.')}
 function send(){if(!text.trim())return;const m={author:'유송민',text:text.trim(),time:'방금'};if(view==='ai'){const r=s.reply(text,data.experiment);setData({...data,student:{...data.student,privateMessages:[...data.student.privateMessages,m,{author:'AI',text:r.text,time:'방금',level:r.level}]},guidance:[...data.guidance,{level:r.level,topic:r.topic,time:'방금'}]})}else setData({...data,student:{...data.student,teamMessages:[...data.student.teamMessages,m]}});setText('')}
 function shareDoc(i:number){setData({...data,student:{...data.student,teamMessages:[...data.student.teamMessages,{author:'유송민',text:'팀 자료를 공유했습니다.',resourceIndex:i,time:'방금'}]}});go('chat')}
 return <div className={`app-shell student-shell fusion-shell unified-shell ${collapsed?'sidebar-collapsed':''}`}><a className="skip-link" href="#student-main">본문으로 이동</a>{drawer&&<button className="sidebar-backdrop" aria-label="메뉴 닫기" onClick={()=>setDrawer(false)}/>}<WorkspaceSidebar student view={view} open={drawer} onNavigate={go} onClose={()=>{setDrawer(false);setCollapsed(true)}} onRole={()=>{setText('');setDrawer(false);onInstructor()}}/>
 <main id="student-main" className="main"><header className="page-header"><div className="title-row"><button className="mobile-menu icon-button" aria-label="수업 메뉴 열기" onClick={()=>{setDrawer(true);setCollapsed(false)}}><Menu size={20}/></button><h1>{studentNavigation.find(n=>n[0]===view)?.[1]}</h1><span className="teach-badge mint">유송민 · 1팀</span></div><p>배운 지식을 연결하고, 직접 수행한 근거로 다음 학습을 이어가세요.</p></header><div className="student-context"><span>{s.course.semester} · {s.course.name}</span><span>가상 수업 · AI와 실습은 시연용입니다.</span></div>{notice&&<p className="settings-notice" role="status">{notice}</p>}
 {view==='team'&&<><section className="panel fusion-overview"><div><h2>{data.plan.name}</h2><p>{data.brief}</p><div className="fusion-phase">{phases.map((p,i)=><span key={p} className={i<phase?'done':i===phase?'current':''}><b>{i<phase?<Check size={14}/>:i+1}</b>{p}</span>)}</div></div><div className="fusion-overview-action"><ProgressRing value={progress} label="팀 과제 진행률"/><button className="button primary" onClick={()=>go('studio')}>작업실 이어가기 <ArrowRight size={16}/></button></div></section><div className="fusion-split"><Panel title="우리 팀의 과제와 계획" action={<button className="text-button" onClick={()=>{setTab('기획·기술 선택');go('studio')}}>기획 수정 →</button>}><div className="fusion-purpose"><div><span>대상과 문제</span><strong>{data.plan.audience}</strong><p>{data.plan.problem}</p></div><div><span>이번 수행 범위</span><strong>{data.plan.scope}</strong><p>{data.plan.language} · {data.plan.frontend} · {data.plan.backend}</p></div></div><p className="fusion-choice-reason"><Link2 size={17}/>{data.plan.reason}</p></Panel><Panel title="지금 필요한 배움"><h3>{s.needTitle}</h3><p className="section-note">{s.need}</p><div className="student-check-list">{s.tasks.slice(1,4).map(t=><span key={t.id} className={data.completed.includes(t.id)?'done':''}><Check size={17}/>{t.title}</span>)}</div><button className="text-button" onClick={()=>go('ai')}>내 질문에서 시작하기 →</button></Panel></div><Panel title="팀원별 현재 수행"><div className="fusion-member-grid">{members.map(([name,role,activity],i)=><div key={name}><span className={`member-avatar member-${i}`}>{name[0]}</span><div><strong>{name}{i===0?' · 나':''}</strong><small>{role}</small><p>{i===0&&data.experiment?'검증 근거 공유 완료':activity}</p></div></div>)}</div></Panel><Panel title="교수자에게 받은 지도"><p>{data.feedbackSent?data.teacherFeedback:'아직 받은 지도 내용이 없습니다. 시도한 내용과 질문을 정리해 지도를 요청할 수 있어요.'}</p><button className="text-button" onClick={()=>go('ai')}>지도 요청과 후속 수행 →</button></Panel><Panel title="지식 연결과 적용 계획"><KnowledgeConnections/></Panel><Panel title="팀 자료와 공유 기록"><div className="student-resource-list">{data.student.resources.slice(0,4).map((r,i)=><button key={i} onClick={()=>setResource(i)}><Files size={20}/><span><strong>{r.name}</strong><small>{r.kind}</small></span><ArrowRight size={16}/></button>)}</div><button className="text-button" onClick={()=>go('documents')}>팀 자료 전체 보기 →</button></Panel></>}
 {view==='studio'&&<><div className="compact-tabs fusion-studio-tabs">{['기획·기술 선택','수행 보드','실행 및 검증'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='기획·기술 선택'?<><Panel title="문제에서 수행 계획까지"><p className="section-note">해결할 문제와 최소 범위를 정하고, 배운 지식과 필요한 도구를 연결하세요.</p><div className="fusion-plan-grid">{([['name','프로젝트 이름'],['audience','대상 사용자'],['problem','해결할 문제'],['scope','첫 수행에서 확인할 최소 범위'],['language','언어·명령 체계'],['frontend','화면·구성 도구'],['backend','처리·연결 방식'],['tools','자료·설계·협업 도구']] as const).map(([k,label])=><label className="field" key={k}>{label}<input value={plan[k]} placeholder={s.project.plan[k]} onChange={e=>setPlan({...plan,[k]:e.target.value})}/></label>)}</div><label className="field">이미 배운 것, 새로 배울 것과 선택 이유<textarea rows={4} value={plan.reason} placeholder={s.project.plan.reason} onChange={e=>setPlan({...plan,reason:e.target.value})}/></label><button className="button primary" onClick={savePlan}>선택 이유와 기획 저장</button></Panel><Panel title="지식 연결과 적용 계획"><KnowledgeConnections editable/></Panel></>:tab==='수행 보드'?<><Panel title="작은 작업으로 나누기"><div className="fusion-kanban">{['할 일','진행 중','완료'].map(col=><section key={col}><h3>{col}</h3>{s.tasks.filter(t=>(data.completed.includes(t.id)?'완료':t.stage==='완료'?'진행 중':t.stage)===col).map(t=><button key={t.id} aria-pressed={task===t.id} onClick={()=>setTask(t.id)}><strong>{t.title}</strong><small>{t.id==='schema'||t.id==='contract'||t.id==='reflect'?'유송민':'팀 공동 수행'}</small><p>{t.detail}</p></button>)}</section>)}</div></Panel><Panel title="수행과 판단 기록"><p>{s.tasks.find(t=>t.id===task)?.title}</p><label className="field">내가 직접 한 행동과 확인 결과<textarea rows={4} value={workNote} placeholder={s.guidance} onChange={e=>setWorkNote(e.target.value)}/></label><button className="button primary" disabled={!workNote.trim()} onClick={()=>{setData({...data,completed:[...new Set([...data.completed,task])],evidence:[...data.evidence,{title:s.tasks.find(t=>t.id===task)!.title,detail:workNote,owner:'유송민',source:'수행 보드 · 학생 설명',criterion:'해결 과정',time:'방금'}]});setWorkNote('');setNotice('수행 근거를 저장했습니다.')}}>수행 근거 저장</button></Panel></>:<ProjectSimulation/>}</>}
 {(view==='chat'||view==='ai')&&<div className="student-chat-layout"><Panel title={view==='ai'?'개인 학습 지원':'팀 대화'} action={<span className="teach-badge mint">{view==='ai'?'개인 공간':'팀 공유'}</span>}><p className="course-demo-note">{view==='ai'?'맥락에 따른 가이드 예시입니다. 개인 대화 원문은 교수자에게 표시하지 않습니다.':'작성한 메시지와 자료를 팀 공간에 모읍니다. 현재는 로컬 시연입니다.'}</p><div ref={log} className="student-messages" role="log" aria-label={view==='ai'?'개인 대화':'팀 대화'}>{(view==='ai'?data.student.privateMessages:data.student.teamMessages).map((m,i)=><div key={i} className={`student-message ${m.author==='유송민'?'mine':''}`}><div><strong>{m.author==='AI'?'TRACE AI':m.author}</strong><time>{m.time}</time></div><p>{m.text}</p>{m.resourceIndex!==undefined&&data.student.resources[m.resourceIndex]&&<button className="chat-document-link" onClick={()=>setResource(m.resourceIndex!)}><Files size={18}/>{data.student.resources[m.resourceIndex].name}</button>}</div>)}</div><div className="student-prompts">{(view==='ai'?s.prompts:['오늘 확인한 내용 공유','다음 수행과 역할 합의','검증 결과 비교']).map(p=><button key={p} className="text-button" onClick={()=>setText(p)}>{p}</button>)}</div><form className="student-composer" onSubmit={e=>{e.preventDefault();send()}}><label className="field">{view==='ai'?'개인 질문':'팀 메시지'}<textarea rows={3} maxLength={2000} value={text} onChange={e=>setText(e.target.value)} placeholder={view==='ai'?s.prompts[0]:'확인한 내용과 다음 행동을 팀원에게 남겨 주세요.'}/></label><div><button type="button" className="text-button" onClick={()=>go(view==='ai'?'studio':'documents')}>{view==='ai'?'작업실에서 확인 →':'팀 자료 공유 →'}</button><button className="button primary" disabled={!text.trim()}>{view==='ai'?'AI에게 질문하기':'팀에 보내기'}</button></div></form></Panel><aside><Panel title="현재 수행 맥락"><h3>{data.plan.name}</h3><p>{data.plan.scope}</p><h3>다음에 확인할 것</h3><p className="section-note">{s.need}</p></Panel><Panel title="교수자에게 함께 점검받기"><label className="field">공유할 지도 요청<textarea rows={4} value={request} onChange={e=>setRequest(e.target.value)} placeholder={s.project.request}/></label><button className="button secondary" disabled={!request.trim()} onClick={()=>{setData({...data,request:request.trim(),feedbackSent:false});setNotice('교수자 팀별 모니터링에 지도 요청을 남겼습니다.')}}>지도 요청 보내기</button><p className="fusion-feedback">{data.feedbackSent?data.teacherFeedback:'교수자 답변을 기다리거나, 시도한 내용과 함께 질문을 남겨 주세요.'}</p></Panel></aside></div>}
 {view==='learning'&&<><div className="fusion-split"><Panel title="나의 수행과 근거"><div className="fusion-personal-metrics"><ProgressRing value={progress} label="현재 과제 수행 진행률"/><div><strong>{data.evidence.filter(e=>e.owner==='유송민').length}개 수행 기록</strong><p>{data.connections.length}개 지식 연결 · {data.experiment?'검증 결과 기록 있음':'실행 결과 확인 필요'}</p><small>수행 진행과 근거 수 · 성적이 아닙니다.</small></div></div></Panel><Panel title="지난 과제에서 이번 수행으로"><p className="section-note">{s.previousGap}</p><button className="text-button" onClick={()=>{setTab('실행 및 검증');go('studio')}}>이번 검증에서 확인하기 →</button></Panel></div><Panel title="내가 수행한 Learning Evidence"><div className="fusion-evidence-list">{data.evidence.filter(e=>e.owner==='유송민').map((e,i)=><button key={i} onClick={()=>evidence(e)}><Files size={20}/><span><strong>{e.title}</strong><small>{e.source} · {e.criterion}</small><p>{e.detail}</p></span><ArrowRight size={17}/></button>)}</div></Panel><Panel title="지식 연결과 적용 계획"><KnowledgeConnections editable/></Panel><Panel title="교수자 지도와 평가 피드백"><h3>수행 지도</h3><p>{data.feedbackSent?data.teacherFeedback:'아직 전달된 지도가 없습니다.'}</p><h3>저장된 평가 피드백</h3><p>{data.reviews['유송민']?.feedback||'교수자가 평가 검토 후 저장한 피드백이 표시됩니다.'}</p></Panel></>}
 <TeamDocuments data={data.student} onUpdate={student=>setData({...data,student})} openIndex={resource} onClose={()=>setResource(null)} onOpen={setResource} onShare={shareDoc} full={view==='documents'}/>
 </main><dialog ref={dialog} className="student-resource-dialog" aria-labelledby="project-evidence-title"><div className="section-heading"><h2 id="project-evidence-title">{detail?.title}</h2><button className="text-button" onClick={()=>dialog.current?.close()}>닫기</button></div><span className="teach-badge mint">{detail?.owner} · {detail?.criterion}</span><p className="section-note">{detail?.source}</p><pre>{detail?.detail}</pre></dialog></div>
}
