import { useRef, useState } from 'react'
import { type Assignment, demoStudents } from './assignment'
import './teaching.css'

export type TeachingView = 'monitoring' | 'evaluation'
type Status = '정상' | '확인 필요' | '지연' | '승인 대기'
type Team = { id: number; progress: number; stage: string; status: Status; recent: string; summary: string; reasons: string[] }
const teams: Team[] = [
  { id: 1, progress: 72, stage: '원인 분석', status: '정상', recent: '5분 전', summary: '진단 결과를 비교하며 원인을 좁히고 있습니다. 다음 단계에서 복구 후 검증 기록이 남는지 확인해 주세요.', reasons: ['원인 후보 3개 중 2개 제외', '진단 근거를 팀 문서에 정리 중'] },
  { id: 2, progress: 48, stage: '문제 진단', status: '확인 필요', recent: '18분 전', summary: '같은 VLAN 설정을 반복 수정하고 있으며 아직 검증 단계로 넘어가지 못했습니다. 수정의 근거를 설명할 수 있는지 확인이 필요합니다.', reasons: ['18분간 수행 단계 변화 없음', '동일 VLAN 설정 3회 수정', '변경 후 Ping 검증 기록 없음'] },
  { id: 3, progress: 66, stage: '수정 단계', status: '승인 대기', recent: '3분 전', summary: '일부 단말의 연결은 복구했지만 전체 경로 검증은 남아 있습니다. 검증 범위를 넓히는 상황 제안이 승인 대기 중입니다.', reasons: ['단일 단말에서만 복구 확인', '다른 대역의 검증 기록 필요'] },
  { id: 4, progress: 35, stage: '문제 진단', status: '지연', recent: '32분 전', summary: '원인 후보를 정한 뒤 새로운 진단 기록이 없습니다. 도구 사용의 어려움인지 역할 조정이 필요한지 확인해 주세요.', reasons: ['32분간 새 수행 기록 없음', '중간 점검 목표보다 1단계 지연'] },
  { id: 5, progress: 84, stage: '결과 검증', status: '정상', recent: '2분 전', summary: '복구 전·후 결과를 비교하고 있습니다. 반복 검증의 조건이 기록되었는지 확인하면 좋겠습니다.', reasons: ['복구 결과 2회 재검증', '보고서에 비교 결과 작성 중'] },
  { id: 6, progress: 61, stage: '수정 단계', status: '정상', recent: '7분 전', summary: '라우팅 경로를 수정하고 역할별 점검을 진행하고 있습니다. 팀원 간 점검 결과 공유가 이어지고 있습니다.', reasons: ['역할별 진단 결과 공유 완료', '수정 후 검증 준비 중'] },
]
const roles = ['네트워크 설정·검증', '장애 원인 분석', '진단 도구 운영', '과정 기록·공유']
const members = (id: number) => demoStudents.filter((_, i) => i % 6 === id - 1)
const teamOf = (student: string) => demoStudents.indexOf(student) % 6 + 1
const roleOf = (student: string) => roles[Math.floor(demoStudents.indexOf(student) / 6)]
const tone = (status: string) => status === '정상' || status === '충분' ? 'mint' : status === '승인 대기' || status === '진행 중' ? 'lavender' : status === '지연' || status === '부족' ? 'rose' : 'yellow'
function Badge({ value }: { value: string }) { return <span className={`teach-badge ${tone(value)}`}>{value}</span> }
type Review = { judgments: Record<string, string>; feedback: string }
function loadReviews(): Record<string, Review> { try { return JSON.parse(localStorage.getItem('trace-reviews') || '{}') || {} } catch { return {} } }

export function TeachingWorkspace({ view, assignment, onNavigate }: { view: TeachingView; assignment: Assignment; onNavigate: (view: TeachingView) => void }) {
  const [task, setTask] = useState('current')
  const [teamId, setTeamId] = useState(2)
  const [student, setStudent] = useState('이서연')
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('전체')
  const [decisions, setDecisions] = useState<Record<string, string>>({})
  const [approvedSituations, setApprovedSituations] = useState<Record<string, string>>({})
  const [reviews, setReviews] = useState(loadReviews)
  const [notice, setNotice] = useState('')
  const [dialogType, setDialogType] = useState<'approval' | 'guidance' | 'detail'>('detail')
  const [draft, setDraft] = useState('')
  const dialog = useRef<HTMLDialogElement>(null)
  const title = task === 'current' ? assignment.title : 'VLAN 분리 및 부서 간 통신 검증'
  const approvalMode = task === 'current' ? assignment.mode === '교수자 승인형' : false
  const displayedTeams = teams.map(t => ({ ...t, status: (t.status === '승인 대기' && (!approvalMode || decisions[`${task}-${t.id}`]) ? '정상' : t.status) as Status, progress: task === 'current' ? t.progress : Math.max(20, t.progress - 12), stage: task === 'current' ? t.stage : t.id % 2 ? 'VLAN 구성' : '통신 검증' }))
  const selected = { ...displayedTeams.find(t => t.id === teamId)! }
  if (teamId === 3 && (!approvalMode || decisions[`${task}-${teamId}`])) selected.summary = decisions[`${task}-${teamId}`] === '거절' ? '제안된 상황은 적용하지 않았습니다. 일부 단말만 복구한 상태로, 전체 경로의 검증 진행을 확인해 주세요.' : decisions[`${task}-${teamId}`] ? '검증 범위를 넓히는 상황을 승인했습니다. 후속 수행 기록에서 다른 대역의 검증 여부를 확인해 주세요.' : '일부 단말의 연결은 복구했지만 전체 경로 검증은 남아 있습니다. 다른 대역에서도 같은 결과를 얻는지 확인해 주세요.'
  const activityMinutes = parseInt(selected.recent)
  const clockAt = (minutesAgo: number) => { const minutes = 14 * 60 + 24 - minutesAgo; return `${Math.floor(minutes / 60)}:${String(minutes % 60).padStart(2,'0')}` }
  const studentTeam = displayedTeams.find(t => t.id === teamOf(student))!
  const reviewKey = `${task}-${student}`
  const review = reviews[reviewKey] || { judgments: {}, feedback: '' }
  const criterionList = task === 'current' ? assignment.criteria : [{ name: '문제 이해', weight: 20 }, { name: '해결 과정', weight: 30 }, { name: '검증', weight: 30 }, { name: '협업', weight: 20 }]
  const needsCheck = studentTeam.status === '확인 필요' || studentTeam.status === '지연'
  const studentRole = roleOf(student)
  const actions = studentRole === roles[0] ? ['라우팅 설정과 주소 대역 확인', 'VLAN ID 수정 및 변경 이유 기록', needsCheck ? '수정 후 연결 상태 검증 준비' : 'Ping 재실행 및 정상 응답 확인'] : studentRole === roles[1] ? ['장애 증상과 영향 범위 분류', 'VLAN 불일치를 원인 후보로 제시', '정상 단말과 장애 단말의 설정 비교'] : studentRole === roles[2] ? ['Ping으로 통신 실패 구간 확인', 'traceroute로 전달 경로 점검', needsCheck ? '검증 명령과 대상 단말 정리' : '수정 전·후 응답 결과 비교'] : ['팀원의 진단 결과 취합', 'VLAN 수정 과정과 판단 근거 기록', needsCheck ? '미완료 검증 항목을 팀 문서에 표시' : '검증 결과를 보고서에 정리']
  function openDialog(kind: typeof dialogType) { setDialogType(kind); setDraft(kind === 'approval' ? '다른 VLAN의 단말에서도 통신이 가능한지 확인해야 하는 상황을 제시합니다.' : '설정을 바꾸기 전과 후에 무엇이 달라졌나요? 원인 후보를 하나 정하고, 이를 확인할 검증 방법을 설명해 보세요.'); dialog.current?.showModal() }
  function decide(value: string) { setDecisions(prev => ({ ...prev, [`${task}-${teamId}`]: value })); if (value === '수정 후 승인') setApprovedSituations(prev => ({ ...prev, [`${task}-${teamId}`]: draft })); setNotice(`${teamId}팀의 AI 제안을 ${value}했습니다.`) }
  function updateReview(next: Partial<Review>) { setReviews(prev => ({ ...prev, [reviewKey]: { ...review, ...next } })); setNotice('') }
  function saveReview() { try { localStorage.setItem('trace-reviews', JSON.stringify(reviews)); setNotice(`${student} 학생의 평가와 피드백을 이 브라우저에 저장했습니다.`) } catch { setNotice('저장하지 못했습니다. 브라우저 저장 공간을 확인해 주세요.') } }
  function showStudent(name: string) { setStudent(name); setQuery(''); onNavigate('evaluation'); window.scrollTo(0, 0) }
  return <div className="teaching-workspace">
    <div className="teaching-toolbar"><div className="task-selector"><label htmlFor="teaching-task">진행 중인 과제</label><select id="teaching-task" value={task} onChange={e => { setTask(e.target.value); setNotice('') }}><option value="current">{assignment.title}</option><option value="vlan">VLAN 분리 및 부서 간 통신 검증</option></select></div>{view === 'evaluation' ? <div className="student-search"><label htmlFor="student-search">학생 검색</label><input id="student-search" type="search" placeholder="이름 또는 팀 검색" value={query} onChange={e => setQuery(e.target.value)} /></div> : <span className="snapshot-label">수업 현황 · 14:24 기준</span>}</div>
    <p className="teaching-demo">시연용 학생·수행 기록 · AI 요약은 교수자의 확인을 위한 참고 정보입니다.</p>
    {notice && <div role="status" className="teaching-notice">{notice}<button type="button" aria-label="처리 알림 닫기" onClick={() => setNotice('')}>닫기</button></div>}
    {view === 'monitoring' ? <>
      <div className="monitor-metrics">{[['전체 팀', displayedTeams.length, 'mint'], ['정상 진행', displayedTeams.filter(t => t.status === '정상').length, 'lavender'], ['확인 필요', displayedTeams.filter(t => ['확인 필요','지연'].includes(t.status)).length, 'yellow'], ['승인 대기', displayedTeams.filter(t => t.status === '승인 대기').length, 'rose']].map(([label, count, color]) => <div className="panel metric" key={label}><span>{label}</span><strong>{count}<small>팀</small></strong><span className={`metric-swatch ${color}`} aria-hidden="true" /></div>)}</div>
      <div className="monitor-layout"><section className="panel team-list-panel"><div className="section-heading"><h2>팀 진행 현황</h2><span className="count-label">평균 {Math.round(displayedTeams.reduce((sum,t) => sum + t.progress,0) / displayedTeams.length)}%</span></div><div className="monitor-filters" aria-label="팀 상태 필터">{['전체','확인 필요','지연','승인 대기'].map(value => <button type="button" key={value} aria-pressed={filter === value} onClick={() => setFilter(value)}>{value}</button>)}</div><div className="team-table-scroll"><table className="team-table"><thead><tr><th>팀 / 진행률</th><th>수행 단계</th><th>상태</th><th>최근 활동</th><th>필요 액션</th></tr></thead><tbody>{displayedTeams.filter(t => filter === '전체' || t.status === filter).map(t => <tr key={t.id} className={teamId === t.id ? 'selected' : ''}><td><button type="button" className="team-select" aria-pressed={teamId === t.id} onClick={() => setTeamId(t.id)}><strong>{t.id}팀</strong><span>{t.progress}%</span><progress value={t.progress} max="100" aria-label={`${t.id}팀 진행률`} /></button></td><td>{t.stage}</td><td><Badge value={t.status} /></td><td>{t.recent}</td><td><button className="text-button" onClick={() => setTeamId(t.id)}>{t.status === '승인 대기' ? '제안 검토' : t.status === '정상' ? '현황 보기' : '진행 확인'}</button></td></tr>)}</tbody></table></div>{!displayedTeams.some(t => filter === '전체' || t.status === filter) && <p className="teaching-empty">해당 상태의 팀이 없습니다.</p>}<div className="monitor-list-note"><strong>지금 살펴볼 팀</strong><p>2팀의 반복 수정과 4팀의 활동 지연을 확인해 주세요. 상태 표시는 평가 점수가 아닙니다.</p></div></section>
      <section className="panel team-detail" aria-label="선택 팀 상세"><div className="section-heading"><h2>{teamId}팀 <span className="detail-percent">{selected.progress}%</span></h2><Badge value={selected.status} /></div><div className="detail-meta"><span>{selected.stage}</span><span>최근 활동 {selected.recent}</span></div><progress className="detail-progress" max="100" value={selected.progress} aria-label="선택 팀 진행률" />
        <section className="detail-section"><h3>AI 상태 요약</h3><p>{selected.summary}</p><ul className="reason-list">{selected.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul></section>
        {approvalMode && teamId === 3 && <section className="approval-request"><div className="section-heading"><h3>AI 개입 제안</h3><Badge value={decisions[`${task}-${teamId}`] || '승인 대기'} /></div><p><strong>상황</strong> {approvedSituations[`${task}-${teamId}`] || '다른 VLAN의 단말에서만 통신이 실패하는 상황'}</p><p><strong>이유</strong> 단일 단말의 성공만으로 복구를 판단하고 있습니다.</p><p><strong>학습 목적</strong> 검증 대상을 넓히고 판단 근거를 설명하기</p>{!decisions[`${task}-${teamId}`] && <div className="compact-actions"><button className="button primary" onClick={() => decide('승인')}>승인</button><button className="button secondary" onClick={() => openDialog('approval')}>수정 후 승인</button><button className="text-button" onClick={() => decide('거절')}>거절</button></div>}</section>}
        {approvedSituations[`${task}-${teamId}`] && <p className="evidence-caption"><strong>승인한 수정 상황</strong><br />{approvedSituations[`${task}-${teamId}`]}</p>}
        <section className="detail-section"><h3>팀원 역할 현황</h3><div className="member-rows">{members(teamId).map((name,i) => <div key={name}><button className="text-button" onClick={() => showStudent(name)}>{name}</button><span>{roles[i]}</span><small>{activityMinutes + i}분 전</small></div>)}</div></section>
        <section className="detail-section"><h3>주요 이벤트</h3><ol className="event-timeline">{[[clockAt(activityMinutes + 19),'문제 상황 시작'],[clockAt(activityMinutes + 13),'Ping 테스트 실행'],[clockAt(activityMinutes + 9),'VLAN 설정 변경'],[clockAt(activityMinutes),teamId === 2 ? '동일 설정 재수정' : '변경 결과 팀 공유'],['14:24',teamId === 3 && approvalMode ? '시스템 · AI 개입 제안 확인' : '시스템 · 수행 기록 현황 확인']].map(([time,event]) => <li key={time}><time>{time}</time><span>{event}</span></li>)}</ol></section>
        <div className="detail-actions"><button className="button secondary" onClick={() => openDialog('detail')}>팀 상세 보기</button><button className="button primary" onClick={() => openDialog('guidance')}>가이던스 제안</button></div>
      </section></div>
    </> : <div className="evaluation-layout"><aside className="panel student-list" aria-label="학생 목록"><div className="section-heading"><h2>학생</h2><span className="count-label">24명</span></div>{demoStudents.filter(name => `${name} ${teamOf(name)}팀`.includes(query.trim())).map(name => <button type="button" key={name} className={`student-select ${name === student ? 'selected' : ''}`} onClick={() => { setStudent(name); setNotice('') }}><span><strong>{name}</strong><small>{teamOf(name)}팀</small></span><span>{roleOf(name)}</span><Badge value={teamOf(name) === 2 || teamOf(name) === 4 ? '확인 필요' : '진행 중'} /></button>)}{!demoStudents.some(name => `${name} ${teamOf(name)}팀`.includes(query.trim())) && <p className="teaching-empty">검색 결과가 없습니다.</p>}</aside>
      <div className="student-review"><section className="panel student-overview"><div className="section-heading"><h2>{student}<span className="student-team-label">{studentTeam.id}팀</span></h2><button className="text-button" onClick={() => { setTeamId(studentTeam.id); onNavigate('monitoring'); window.scrollTo(0,0) }}>팀 보기</button></div><p className="student-role">{studentRole}</p><div className="detail-meta"><span>{title}</span><span>현재 단계 · {studentTeam.stage}</span></div><h3>학생 수행 요약</h3><div className="learning-states">{[['문제 이해','충분'],['원인 분석','진행 중'],['도구 활용','충분'],['검증',needsCheck ? '확인 필요' : '충분'],['자기 설명',needsCheck ? '진행 중' : '충분']].map(([label,state]) => <div key={label}><span>{label}</span><Badge value={state} /></div>)}</div></section>
        <section className="panel learning-detail"><div><h2>역할 수행</h2><p className="section-note">{studentRole}</p><ul className="performed-actions">{actions.map(action => <li key={action}>{action}</li>)}</ul></div><div><h2>이해도 / 학습 상태</h2><dl className="concept-list">{[['네트워크 주소 체계','안정적으로 적용'],['VLAN 개념','적용 가능'],['라우팅 진단',needsCheck ? '추가 확인 필요' : '경로 비교 가능'],['검증 과정',needsCheck ? '보완 필요' : '반복 검증 수행']].map(([concept,state]) => <div key={concept}><dt>{concept}</dt><dd>{state}</dd></div>)}</dl><p className="evidence-caption">{needsCheck ? '설정 변경은 기록되어 있으나 변경 후 검증 근거가 아직 충분하지 않습니다.' : '수정 전·후 결과를 비교하고 정상 응답을 확인한 기록이 있습니다.'}</p></div></section>
        <section className="panel evidence-panel"><div className="section-heading"><h2>Learning Evidence</h2><span className="count-label">핵심 과정증거 · 14:08–14:21</span></div><div className="evidence-flow">{[['문제 판단','VLAN 불일치를 장애 원인 후보로 판단'],['근거','Ping 실패와 정상·장애 단말의 VLAN 설정 차이 확인'],['행동 / 수정',actions[1]],['검증',needsCheck ? '재검증 결과 미기록 · 교수자 확인 필요' : 'Ping 재실행 후 정상 응답, 다른 단말에서 재확인']].map(([label,content],i) => <div key={label}><span className={`evidence-step step-${i}`}>{label}</span><p>{content}</p></div>)}</div><p className="evidence-caption">AI가 VLAN 비교를 제안한 뒤 학생이 실제 설정을 확인하고 수행 기록에 근거를 남겼습니다.</p></section>
        <section className="panel ai-support-record"><h2>AI 지원 내역</h2><div className="ai-use-counts"><span>확인 질문 <strong>3회</strong></span><span>개념 힌트 <strong>1회</strong></span><span>도구 활용 힌트 <strong>1회</strong></span><span>직접 답안 제공 <strong>없음</strong></span></div><p>{needsCheck ? 'AI 지원 이후 학생이 직접 설정을 수정했습니다. 검증 수행 여부는 추가 확인이 필요합니다.' : 'AI 지원 이후 학생이 직접 수정하고 결과를 검증했습니다.'}</p><small>개인 AI 채팅 원문은 공개하지 않습니다.</small></section>
        <section className="panel instructor-evaluation"><div className="section-heading"><h2>교수자 평가</h2><span className="count-label">과제의 평가 기준</span></div><p className="section-note">AI는 과정증거만 정리합니다. 최종 판단은 교수자가 기록합니다.</p><table className="evaluation-table"><thead><tr><th>평가 요소</th><th>AI 근거 정리</th><th>교수자 판단</th></tr></thead><tbody>{criterionList.map((criterion,i) => <tr key={`${criterion.name}-${i}`}><td><strong>{criterion.name}</strong><small>{criterion.weight}%</small></td><td>{/검증/.test(criterion.name) ? needsCheck ? '후속 검증 기록 확인 필요' : '전·후 비교 기록 있음' : /협업/.test(criterion.name) ? '역할별 기록 공유 확인' : /산출물/.test(criterion.name) ? '진단 보고서 작성 중' : '수행 기록과 판단 근거 있음'}</td><td><select aria-label={`${criterion.name} 교수자 판단`} value={review.judgments[criterion.name] || ''} onChange={e => updateReview({ judgments: { ...review.judgments, [criterion.name]: e.target.value } })}><option value="">판단 선택</option>{['우수','충분','적절','보완 필요','판단 보류'].map(value => <option key={value}>{value}</option>)}</select></td></tr>)}</tbody></table><div className="field feedback-field"><label htmlFor="instructor-feedback">교수자 피드백</label><textarea id="instructor-feedback" rows={3} placeholder="학생이 잘한 점과 다음에 확인할 내용을 기록하세요." value={review.feedback} onChange={e => updateReview({ feedback: e.target.value })} /></div><div className="review-save"><span>학생별로 이 브라우저에 저장됩니다.</span><button className="button primary" onClick={saveReview}>평가 저장</button></div></section>
      </div></div>}
    <dialog ref={dialog} className="teaching-dialog"><div className="section-heading"><h2>{teamId}팀 · {dialogType === 'detail' ? '수행 상세' : dialogType === 'approval' ? '제안 수정 후 승인' : '가이던스 제안'}</h2><button className="text-button" onClick={() => dialog.current?.close()}>닫기</button></div>{dialogType === 'detail' ? <><p>{selected.summary}</p><h3>현재 공유 문서</h3><p>장애 진단 보고서 · 원인 후보와 설정 변경 기록 작성 중</p><h3>팀원별 수행 근거</h3><div className="member-rows">{members(teamId).map(name => <div key={name}><span>{name} · {roleOf(name)}</span><button className="text-button" onClick={() => { dialog.current?.close(); showStudent(name) }}>평가 근거 보기</button></div>)}</div></> : <><label htmlFor="guidance-draft">{dialogType === 'approval' ? '학생에게 적용할 상황' : '학생의 사고를 이끌 질문'}</label><textarea id="guidance-draft" rows={5} value={draft} onChange={e => setDraft(e.target.value)} /><p className="micro-note">시연에서는 제안과 처리 상태만 기록됩니다.</p><button className="button primary" disabled={!draft.trim()} onClick={() => { if (dialogType === 'approval') decide('수정 후 승인'); else setNotice(`${teamId}팀 가이던스 제안을 저장했습니다: ${draft}`); dialog.current?.close() }}>{dialogType === 'approval' ? '수정 내용 승인' : '제안 저장'}</button></>}</dialog>
  </div>
}
