import { useEffect, useRef, useState } from 'react'
import { FileText, Paperclip, Search, Download, Send, X, Pencil, Plus, FolderOpen } from 'lucide-react'
import type { StudentState, TeamResource } from './student'
export function TeamDocuments({data,onUpdate,openIndex,onClose,onOpen,onShare,full}:{data:StudentState;onUpdate:(d:StudentState)=>void;openIndex:number|null;onClose:()=>void;onOpen:(i:number)=>void;onShare:(i:number)=>void;full:boolean}) {
  const [search,setSearch]=useState(''),[filter,setFilter]=useState('전체'),[editing,setEditing]=useState(false),[creating,setCreating]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const dialog=useRef<HTMLDialogElement>(null),upload=useRef<HTMLInputElement>(null)
  const item=openIndex===null?null:data.resources[openIndex]
  useEffect(()=>{if(openIndex!==null){dialog.current?.showModal()}else if(!creating)dialog.current?.close()},[openIndex,creating])
  function close(){setCreating(false);setEditing(false);setError('');dialog.current?.close();onClose()}
  function create(){setTitle('');setBody('');setEditing(true);setCreating(true);setError('');dialog.current?.showModal()}
  function save(){if(!title.trim()||!body.trim()){setError('문서 제목과 내용을 입력해 주세요.');return}const doc:TeamResource={...(!creating&&item?item:{}),id:creating?undefined:item?.id||(item?.name==='양방향 복구 검증'?'network-verification':undefined),name:title.trim(),body:body.trim(),kind:creating?'팀 문서':item?.kind||'팀 문서',author:'유송민',updated:new Date().toLocaleDateString('ko-KR'),version:(creating?0:item?.version??1)+1};const resources=[...data.resources];if(creating)resources.push(doc);else if(openIndex!==null)resources[openIndex]=doc;onUpdate({...data,resources});setCreating(false);setEditing(false);setError('');if(creating)onOpen(resources.length-1)}
  async function addFiles(list:FileList|null){if(!list?.length)return;const files=Array.from(list);if(files.some(f=>f.size>2*1024*1024)){setError('파일당 2MB 이하로 첨부해 주세요.');return}setBusy(true);setError('');try{const attached=await Promise.all(files.map(f=>new Promise<TeamResource>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('파일을 읽지 못했습니다.'));reader.onload=()=>resolve({name:f.name,kind:'첨부 파일',body:'팀에서 공유한 원본 파일입니다. 다운로드하여 열 수 있습니다.',author:'유송민',updated:new Date().toLocaleDateString('ko-KR'),version:1,dataUrl:String(reader.result),mime:f.type});reader.readAsDataURL(f)})));const next={...data,resources:[...data.resources,...attached]};if(JSON.stringify(next).length>3800000)throw new Error('이 데모의 자료 저장 용량을 초과합니다. 더 작은 파일을 선택해 주세요.');onUpdate(next)}catch(e){setError(e instanceof Error?e.message:'첨부하지 못했습니다. 다시 시도해 주세요.')}finally{setBusy(false)}}
  const visible=data.resources.map((r,i)=>({r,i})).filter(({r})=>`${r.name} ${r.author||''} ${r.body}`.toLowerCase().includes(search.toLowerCase())&&(filter==='전체'||(filter==='문서'?!r.dataUrl:filter==='첨부 파일'?!!r.dataUrl:/검증|Evidence/.test(r.kind))))
  return <><input ref={upload} type="file" hidden multiple onChange={e=>{void addFiles(e.target.files);e.target.value=''}}/>{full&&<section className="panel team-documents"><div className="section-heading"><div><h2>팀의 문서와 파일, 한 곳에서</h2><p className="section-note">작성한 문서와 채팅에서 나눈 자료를 다시 찾고 이어서 작업하세요.</p></div><div className="document-actions"><button className="button secondary" disabled={busy} onClick={()=>upload.current?.click()}><Paperclip size={17}/>{busy?'파일 준비 중…':'파일 첨부'}</button><button className="button primary" onClick={create}><Plus size={17}/>문서 작성</button></div></div><div className="document-toolbar"><label className="document-search"><Search size={18}/><input aria-label="팀 자료 검색" placeholder="문서명, 작성자, 내용 검색" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="compact-tabs">{['전체','문서','첨부 파일','검증 자료'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><span className="count-label">{visible.length}개 자료</span></div>{error&&<p role="alert" className="error-message">{error}</p>}<div className="table-scroll"><table className="reference-table document-table"><thead><tr><th>문서 / 파일</th><th>작성자</th><th>최근 수정</th><th>버전</th><th>공유</th></tr></thead><tbody>{visible.map(({r,i})=><tr key={i}><td><button className="document-name" onClick={()=>{setEditing(false);onOpen(i)}}><span className={`document-type ${r.dataUrl?'attachment':''}`}>{r.dataUrl?<Paperclip size={21}/>:<FileText size={21}/>}</span><span><strong>{r.name}</strong><small>{r.kind}</small></span></button></td><td>{r.author||['강병준','김민수','박지훈'][i%3]}</td><td>{r.updated||'오늘 14:10'}</td><td>v{r.version||1}</td><td><button className="icon-button" aria-label={`${r.name} 팀 채팅에 공유`} onClick={()=>onShare(i)}><Send size={17}/></button></td></tr>)}</tbody></table></div>{!visible.length&&<div className="document-empty"><FolderOpen size={30}/><strong>조건에 맞는 자료가 없어요</strong><span>다른 검색어를 입력하거나 새 문서를 작성하세요.</span></div>}<p className="course-demo-note">데모 자료는 이 브라우저에 저장됩니다. 파일당 2MB까지 첨부할 수 있으며 다른 기기와 동기화되지는 않습니다.</p></section>}
    <dialog ref={dialog} className="student-resource-dialog document-dialog" onCancel={()=>{setCreating(false);setEditing(false);onClose()}} aria-labelledby="document-dialog-title"><div className="section-heading"><h2 id="document-dialog-title">{creating?'새 팀 문서':editing?'팀 문서 수정':item?.name}</h2><button className="icon-button" aria-label="문서 닫기" onClick={close}><X size={20}/></button></div>{editing?<><label className="field">문서 제목<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} autoFocus/></label><label className="field">문서 내용<textarea rows={12} value={body} onChange={e=>setBody(e.target.value)} placeholder="회의 내용, 원인 가설, 실습 과정과 결과를 팀 문서로 남겨보세요."/></label>{error&&<p role="alert" className="error-message">{error}</p>}<div className="dialog-footer"><button className="button secondary" onClick={()=>{if(creating)close();else setEditing(false)}}>취소</button><button className="button primary" onClick={save}>문서 저장</button></div></>:item&&<><div className="document-meta"><span className="teach-badge mint">{item.kind}</span><span>{item.author||'팀 공유 자료'} · v{item.version||1}</span></div><pre>{item.body}</pre><div className="dialog-footer">{!item.dataUrl&&<button className="button secondary" onClick={()=>{setTitle(item.name);setBody(item.body);setEditing(true)}}><Pencil size={17}/>수정</button>}<a className="button secondary" href={item.dataUrl||`data:text/plain;charset=utf-8,${encodeURIComponent(item.body)}`} download={item.dataUrl?item.name:`${item.name}.txt`}><Download size={17}/>다운로드</a><button className="button primary" onClick={()=>{if(openIndex!==null)onShare(openIndex);close()}}><Send size={17}/>팀 채팅에 공유</button></div></>}</dialog>
  </>
}
